homepage: http://plancomps.org
changelog-type: ''
hash: a25fe850c369e5954bac484bb0e896e4f36cd61366ac82d00bd70210f779b248
test-bench-deps: {}
maintainer: L. Thomas van Binsbergen <ltvanbinsbergen@acm.org>
synopsis: Library providing values and operations on values in a fixed universe.
changelog: ''
basic-deps:
  base: ! '>=4.8 && <5'
  text: ! '>=1.2 && <1.3'
  random-strings: -any
  containers: ! '>=0.5 && <0.6'
  bv: ! '>=0.5'
  multiset: ! '>=0.3 && <0.4'
  vector: ! '>=0.12'
all-versions:
- '0.1.0.2'
- '0.1.0.3'
author: L. Thomas van Binsbergen and Neil Sculthorpe
latest: '0.1.0.3'
description-type: haddock
description: ! 'The PLanCompS project (<http://plancomps.org>) has developed a component-based
  approach to formal semantics.

  The semantics of a language is defined by translating its constructs to combinations

  of `fundamental constructs'' called /funcons/.


  This package provides a fixed universe types, values and operations which are lifted
  to funcons as part of the /funcons-tools/ package (<http://hackage.haskell.org/package/funcons-tools>).

'
license-name: MIT
