homepage: http://plancomps.org
changelog-type: ''
hash: 8ebd4266bb651d55316d56701e65431aa063143a8495a83323f3b80a500436ca
test-bench-deps: {}
maintainer: L. Thomas van Binsbergen <ltvanbinsbergen@acm.org>
synopsis: Library providing values and operations on values.
changelog: ''
basic-deps:
  base: ! '>=4.8 && <5'
  text: ! '>=1.2 && <1.3'
  random-strings: -any
  containers: ! '>=0.5 && <0.6'
  bv: ! '>=0.5'
  multiset: ! '>=0.3 && <0.4'
  vector: ! '>=0.12'
all-versions:
- '0.1.0.0'
author: L. Thomas van Binsbergen and Neil Sculthorpe
latest: '0.1.0.0'
description-type: haddock
description: ''
license-name: MIT
