homepage: https://github.com/fimad/prometheus-haskell
changelog-type: ''
hash: 74e2dab495f54138eccc8528b81d1444e2aa310a4cf1e963ae465ca933c86342
test-bench-deps:
  base: ! '>=4.7 && <5'
  doctest: -any
  prometheus-client: -any
maintainer: willcoster@gmail.com
synopsis: WAI middlware for exposing http://prometheus.io metrics.
changelog: ''
basic-deps:
  bytestring: ! '>=0.9'
  wai: ! '>=3.0'
  base: ! '>=4.7 && <5'
  text: ! '>=0.11'
  clock: -any
  data-default: -any
  prometheus-client: -any
  http-types: -any
all-versions:
- '0.1.0.0'
- '0.1.0.1'
- '0.1.1'
- '0.3.0'
author: Will Coster
latest: '0.3.0'
description-type: haddock
description: WAI middlware for exposing http://prometheus.io metrics.
license-name: Apache-2.0
