homepage: https://github.com/trskop/hs-pkg-config
changelog-type: markdown
hash: 014d1b8e4375de3e7d154b6996b9e54917fde4d3d7fec917feaf262576a645ce
test-bench-deps: {}
maintainer: peter.trsko@gmail.com
synopsis: Create pkg-config configuration files
changelog: ! "# ChangeLog / ReleaseNotes\n\n\n## Version 0.2.1.0\n\n* Derive `Generic`
  instance for `PkgConfig`.\n\n* Introduced functions:\n  * `versionInt :: [Int] ->
  PkgTemplate`\n  * `toString :: PkgConfig -> String`\n\n* Building option `-fpedantic`.\n\n*
  Documentation updates.\n\n* Uploaded to [Hackage][]:\n  <http://hackage.haskell.org/package/hs-pkg-config-0.2.1.0>\n\n\n##
  Version 0.2.0.0\n\n* New functions in `Data.PkgCofig` module:\n  * `quote :: PkgTemplate
  -> PkgTemplate`\n  * `option :: Strict.Text -> PkgTemplate -> PkgTemplate`\n  *
  `strOption :: String -> PkgTemplate -> PkgTemplate`\n\n* Quoting option arguments
  by default. This affects following functions from\n  `Data.PkgCofig` module:\n  *
  `includes :: [PkgTemplate] -> PkgTemplate`\n  * `libraryPath :: [PkgTemplate] ->
  PkgTemplate`\n\n* Lot of documentation updates.\n\n* Uploaded to [Hackage][]:\n
  \ <http://hackage.haskell.org/package/hs-pkg-config-0.2.0.0>\n\n\n## Version 0.1.0.0\n\n*
  First public release.\n* Uploaded to [Hackage][]:\n  <http://hackage.haskell.org/package/hs-pkg-config-0.1.0.0>\n\n\n[Hackage]:\n
  \ http://hackage.haskell.org/\n  \"HackageDB (or just Hackage) is a collection of
  releases of Haskell packages.\"\n"
basic-deps:
  base: ! '>=4.6 && <5'
  data-default-class: ==0.*
  text: ! '>=0.11 && <1.3'
all-versions:
- 0.1.0.0
- 0.2.0.0
- 0.2.1.0
author: Peter Trško
latest: 0.2.1.0
description-type: markdown
description: ! "Hs-pkg-config\n=============\n\n[![Hackage](http://img.shields.io/hackage/v/hs-pkg-config.svg)][Hackage:
  hs-pkg-config]\n[![BSD3 License](http://img.shields.io/badge/license-BSD3-brightgreen.svg)][tl;dr
  Legal: BSD3]\n\n\nDescription\n-----------\n\nLibrary for creating [pkg-config][Pkg-config
  Homepage] configuration files from\nHaskell.\n\nOne of the possible usage examples
  of this library is generating `.pc` files\nfrom [Shake build system][Shake Homepage].\n\n\nExample\n-------\n\nFollowing
  Haskell code is able to generate package configuration file named\n`foo.pc` for
  library `foo`:\n\n```haskell\n{-# LANGUAGE OverloadedStrings #-}\nmodule Main (main)\n
  \ where\n\nimport Data.String (IsString)\n\nimport Data.Default.Class (Default(def))\n
  \  -- From data-default-class library:\n   -- http://hackage.haskell.org/package/data-default-class\n\nimport
  Control.Lens\n   -- From lens library:\n   -- http://hackage.haskell.org/package/lens\n\nimport
  Data.PkgConfig\n\n\nlibraryBaseName :: IsString a => a\nlibraryBaseName = \"foo\"\n\nmain
  :: IO ()\nmain = writePkgConfig (libraryBaseName ++ \".pc\") libPkgConfig\n  where\n
  \   libPkgConfig = def\n        & pkgVariables   .~\n            [ (\"prefix\",
  \    \"/usr/local\"              )\n            , (\"includedir\", var \"prefix\"
  </> \"include\")\n            , (\"libdir\",     var \"prefix\" </> \"lib\"    )\n
  \           , (\"arch\",       \"i386\"                    )\n            ]\n        &
  pkgName        .~ libraryBaseName\n        & pkgDescription .~ \"Example pkg-config.\"\n
  \       & pkgVersion     .~ version [1, 2, 3]\n        & pkgCflags      .~ includes
  [var \"includedir\"]\n        & pkgRequires    .~ list\n            [ \"bar\" ~>
  [0], \"bar\" ~<= [3, 1]\n            , \"baz\" ~= [1, 2, 3]\n            ]\n        &
  pkgLibs        .~ options\n            [ libraryPath [var \"libdir\", var \"libdir\"
  </> var \"arch\"]\n            , libraries [libraryBaseName]\n            ]\n```\n\nContent
  of `foo.pc`:\n\n```\nprefix=/usr/local\nincludedir=${prefix}/include\nlibdir=${prefix}/lib\narch=i386\n\nName:
  foo\nDescription: Example pkg-config.\nVersion: 1.2.3\nRequires: bar > 0, bar <=
  3.1, baz = 1.2.3\nCflags: -I\"${includedir}\"\nLibs: -L\"${libdir}\" -L\"${libdir}/${arch}\"
  -lfoo\n```\n\nNow lets see if `pkg-config` would be able to tell us something about
  this\nlibrary:\n\n    $ PKG_CONFIG_PATH=`pwd` pkg-config --modversion foo\n    1.2.3\n\nNote
  that asking for `--cflags` or other options would result in error saying\nthat it
  is unable to find `bar` and `baz` libraries. That is OK, it means that\nit is able
  to parse file correctly, we just hadn't provided `bar.pc` and\n`baz.pc`. If we delete
  lines that define `Requires:` field, then `pkg-config`\nwould be able to give us
  `--cflags`, `--libs`, etc. You can try it.\n\n\nBuilding options\n----------------\n\n*
  `-fpedantic` (disabled by default)\n\n  Pass additional warning flags including
  `-Werror` to GHC during compilation.\n\n\n\n[Hackage: hs-pkg-config]:\n  https://hackage.haskell.org/package/hs-pkg-config\n
  \ \"Hackage: hs-pkg-config\"\n[Pkg-config Homepage]:\n  http://www.freedesktop.org/wiki/Software/pkg-config/\n
  \ \"Pkg-config Homepage\"\n[Shake Homepage]:\n  http://shakebuild.com \n  \"Shake
  Homepage\"\n[tl;dr Legal: BSD3]:\n  https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29\n
  \ \"BSD 3-Clause License (Revised)\"\n"
license-name: BSD-3-Clause
