homepage: http://github.com/YoshikuniJujo/hsConfigure/wiki
changelog-type: ''
hash: ab3264ebf799e07e40fd913b9061197b346a7d84145908566155231e62a45c02
test-bench-deps: {}
maintainer: Yoshikuni Jujo <PAF01143@nifty.ne.jp>
synopsis: By using this package, you can make application configurable.
changelog: ''
basic-deps:
  unix: -any
  base: ==4.*
  filepath: -any
  process: -any
  directory: -any
all-versions:
- '0.1'
- 0.1.0.2
author: Yoshikuni Jujo
latest: 0.1.0.2
description-type: haddock
description: ! 'I inspired by xmonad. Xmonad is configurable by using user''s own
  main.

  This package make your application configurable like xmonad.'
license-name: LicenseRef-LGPL
