homepage: ''
changelog-type: ''
hash: e26e8ab371ccf7d523d0731677d641ee7789457ec20849992e3419e240f83ac6
test-bench-deps: {}
maintainer: DiscipleRayne@gmail.com
synopsis: Simple text configuration file parser library.
changelog: ''
basic-deps:
  base: ==4.*
  containers: ! '>=0.2.0.1'
all-versions:
- '0.2'
- '0.5'
- 0.5.1
- 0.5.2
author: Anthony Simpson
latest: 0.5.2
description-type: text
description: ! 'I havent got around to adding this yet, but I will

  in the next version. For now, generating the haddock

  documentation, and glacing over it should be enough

  to use this library. It''s pretty simple.'
license-name: BSD-3-Clause
