homepage: ''
changelog-type: markdown
hash: 52c2bd3ae55c1e4d605a7f9516693f810f8a37582c27b1944397d6a162a4c658
test-bench-deps:
  shakespeare: -any
  bytestring: -any
  unix: -any
  base: ! '>=4 && <5'
  hspec: -any
  text: -any
  process: -any
  cabal-test-bin: ! '>=0.1.4'
  hspec-test-sandbox: -any
  test-sandbox: -any
maintainer: junji.hashimoto@gmail.com
synopsis: Lightweight development enviroments using test-sandbox
changelog: ! '## 0.1.3


  * Add lauching order directive for config file(yaml)


  ## 0.1.2


  * Update cabal-test (remove setup for running daemon)


  ## 0.1.1


  * Fix Changelog.md

'
basic-deps:
  warp: -any
  shelly: -any
  bytestring: -any
  wai: -any
  unix: -any
  yesod-core: -any
  base: ==4.*
  text: -any
  process: -any
  test-sandbox-compose: -any
  network: -any
  lifted-base: -any
  hastache: -any
  containers: -any
  yesod: -any
  wai-extra: -any
  optparse-applicative: -any
  http-conduit: -any
  test-sandbox: ! '>=0.1'
  aeson: -any
  yaml: -any
  directory: -any
all-versions:
- 0.1.0
- 0.1.1
- 0.1.2
- 0.1.3
author: Junji Hashimoto
latest: 0.1.3
description-type: markdown
description: ! "# Test-Sandbox-Compose: Fast Development Environments Using Test-Sandbox\n\n[![Hackage
  version](https://img.shields.io/hackage/v/test-sandbox-compose.svg?style=flat)](https://hackage.haskell.org/package/test-sandbox-compose)
  \ [![Build Status](https://travis-ci.org/junjihashimoto/test-sandbox-compose.png?branch=master)](https://travis-ci.org/junjihashimoto/test-sandbox-compose)\n\nTest-Sandbox-Compose
  makes development environments for multi-servers using Test-Sandbox.\nEach server
  is defined in test-sandbox-compose.yml.\ntest-sandbox-compose.yml provides following
  functions.\n\n* Mustache template for accessing each resource\n* Before/After-bash-script
  for server-setup\n* Tempolary file, directory and TCP-Port which test-sandbox provides\n\nThis
  project is inspired by Docker Compose(Fig).\n\n## Getting started\n\nInstall this
  from Hackage.\n\n    cabal update && cabal install test-sandbox-compose\n\n\n##
  test-sandbox-compose.yml reference\n\n```\n<service-name1>:\n  cmd: <command-name>\n
  \ args:\n    - <arg1>\n    - <arg2>\n  confs:\n    <conf1>: <conf1 contents>\n    <conf2>:
  <conf2 contents>\n  tempfiles:\n    - <temp1>\n    - <temp2>\n  dirs:\n    - <dir1>\n
  \   - <dir2>\n  ports:\n    - <port1>\n    - <port2>\n  beforescript: <script content>\n
  \ afterscript: <script content>\n<service-name2>\n  ...\n```\n\nExample\n\n```\nzookeeper:\n
  \ cmd: '/usr/share/zookeeper/bin/zkServer.sh'\n  args:\n    - 'start-foreground'\n
  \   - '{{zookeeper_conf_conf}}'\n  tempfiles: []\n  confs:\n    conf: |\n      dataDir={{zookeeper_dir_data}}\n
  \     clientPort={{zookeeper_port_2181}}\n      maxClientCnxns=1000\n  dirs:\n    -
  'data'\n  ports:\n    - '2181'\n```\n\n\n## Commands\n\n\n### Up\n\n```\ntest-sandbox-compose
  up\n```\n\n### Status\n\n```\ntest-sandbox-compose status\n```\n\n### Conf\n\n```\ntest-sandbox-compose
  conf\n```\n\n### Kill\n\n```\ntest-sandbox-compose kill\n```\n\n### Logs\n\n```\ntest-sandbox-compose
  logs\n```\n\n### Destroy\n\n```\ntest-sandbox-compose destroy\n```\n\n### Daemon\n\n```\ntest-sandbox-compose
  daemon\n```\n"
license-name: BSD-3-Clause
