homepage: https://github.com/leptonyu/yam#readme
changelog-type: ''
hash: a280bdc204c7fb1bb815f26aa3d16e2e8441c97fde067f6eb9696693c0ccc07e
test-bench-deps: {}
maintainer: Daniel YU <leptonyu@gmail.com>
synopsis: Yam Configuation
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  unordered-containers: -any
  text: -any
  string-conversions: -any
  aeson: -any
  yaml: -any
all-versions:
- '0.3.1'
author: ''
latest: '0.3.1'
description-type: markdown
description: ! '# yam-config

'
license-name: MIT
