homepage: https://github.com/leptonyu/yam#readme
changelog-type: ''
hash: 059930405128664591720fa60034ff128ac63cf04a907003edbcf6b87edc1714
test-bench-deps: {}
maintainer: Daniel YU <leptonyu@gmail.com>
synopsis: Yam Configuation
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  unordered-containers: -any
  text: -any
  data-default: -any
  vault: -any
  random: -any
  string-conversions: -any
  aeson: -any
  yaml: -any
all-versions:
- '0.3.1'
- '0.3.2'
author: ''
latest: '0.3.2'
description-type: markdown
description: ! '# yam-config

'
license-name: MIT
