homepage: ''
changelog-type: ''
hash: 575103d9fa1ef074a2b419256babaae7be5f5257f37adf3ed2601052415b2d83
test-bench-deps:
  base: ! '>=4.5.0 && <5.0.0'
  unordered-containers: ! '>=0.2.0'
  text: ! '>=0.11.0'
  tasty-quickcheck: ! '>=0.8.0'
  hashable: ! '>=1.2.0'
  tasty: ! '>=0.10.0'
  deepseq: ! '>=1.3'
  QuickCheck: ! '>=2.6.0'
  yaml: ! '>=0.8.10'
maintainer: mitroshin@selectel.org
synopsis: Configuration management
changelog: ''
basic-deps:
  base: ! '>=4.5.0 && <5.0.0'
  unordered-containers: ! '>=0.2.0'
  text: ! '>=0.11.0'
  deepseq: ! '>=1.3'
  yaml: ! '>=0.8.10'
all-versions:
- 0.0.1
- 0.1.0
- 0.2.0
- 0.2.1
- 0.2.2
- 0.2.3
- 0.3.0
- 0.4.0
author: ! 'Fedor Gogolev <knsd@knsd.net>

  Mitroshin Maxim <mitroshin@selectel.org>

  Simon Hengel <sol@typeful.net>'
latest: 0.4.0
description-type: haddock
description: Configuration management
license-name: MIT
