homepage: https://github.com/dogonthehorizon/git-config#readme
changelog-type: ''
hash: 39a3e1cfd2b386c7e5f41171c8f8c9ce7a620b662ff456a2abaad72e66bad999
test-bench-deps:
  tasty-smallcheck: -any
  base: ! '>=4.7 && <5'
  tasty-discover: -any
  tasty-travis: -any
  unordered-containers: -any
  text: -any
  megaparsec: -any
  smallcheck: -any
  smallcheck-series: -any
  git-config: -any
  tasty-hunit: -any
  tasty: -any
maintainer: dogonthehorizon@gmail.com
synopsis: A simple parser for Git configuration files.
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  unordered-containers: -any
  text: -any
  megaparsec: -any
all-versions:
- '0.1.0'
author: Fernando Freire
latest: '0.1.0'
description-type: markdown
description: ! "[![Build Status](https://travis-ci.org/dogonthehorizon/git-config.svg?branch=master)](https://travis-ci.org/dogonthehorizon/git-config)\n\n#
  git-config\n\nA simple parser for [Git configuration] files.\n\n## Getting Started\n\nThis
  project is built using [Stack], make sure you have it installed before\nproceeding.\n\nYou
  can fire up an interactive session like so:\n\n```\nstack ghci\n```\n\nThe library
  can be built or tested like so:\n\n```\n# Building\nstack build\n# Running tests\nstack
  test\n```\n\n## Usage\n\nA Git configuration is a colletion of sections that contain
  mappings of keys\nto values.\n\nFor the sake of simplicity this is represented as
  `[Section]` where a\n`Section` is a collection of section names and a mapping of
  keys to values.\n\nWe can use the parser like so:\n\n```haskell\nimport qualified
  Data.Text.IO as TIO\nimport Text.GitConfig.Parser (parseConfig)\n\nmain :: IO ()\nmain
  = do\n  file <- TIO.readFile \".git/config\"\n  case parseConfig file of\n    Right
  conf ->\n      print conf\n    Left error ->\n      print error\n```\n\nIf you'd
  like to do your own parsing you can import the individual combinators\nfrom the
  `Text.GitConfig.Parser` module.\n\n[Stack]: https://docs.haskellstack.org/en/stable/README/\n[Git
  configuration]: https://git-scm.com/docs/git-config/2.16.0#_syntax\n"
license-name: BSD3
