homepage: https://github.com/anton-dessiatov/Win32-security
changelog-type: ''
hash: f2e69034e8fab3c9570d3637f23387513e7c493f0e4050f934f89355c0cc9a5a
test-bench-deps: {}
maintainer: anton.dessiatov@gmail.com
synopsis: Haskell bindings to a security-related functions of the Windows API
changelog: ''
basic-deps:
  Win32-errors: ! '>=0.2.1'
  base: ! '>=4 && <5'
  text: ! '>=1'
  Win32: ! '>=2'
all-versions:
- '0.1'
- 0.1.1
author: Anton Dessiatov
latest: 0.1.1
description-type: haddock
description: ! 'This package contains bindings for security-related functions of the
  Windows API.

  Its main features are account name/SID lookup and editing securable objects access
  control lists.'
license-name: MIT
