homepage: https://github.com/ConferHealth/composite#readme
changelog-type: ''
hash: 8010e2ed63aed5a4824feba8207fa99357e7fff16dbe9cb7a2d3ea52a5f8bb0c
test-bench-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  composite-swagger: -any
  base: ! '>=4.7 && <5'
  composite-base: -any
  hspec: -any
  text: ! '>=1.2.2.2 && <1.3'
  vinyl: ! '>=0.5.3 && <0.12'
  lens: ! '>=4.15.4 && <4.18'
  swagger2: ! '>=2.1.6 && <2.5'
  QuickCheck: -any
  composite-aeson: -any
  template-haskell: ! '>=2.11.1.0 && <2.15'
maintainer: oss@confer.health
synopsis: Swagger for Vinyl/Frames records
changelog: ''
basic-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  base: ! '>=4.7 && <5'
  composite-base: ! '>=0.5.3.0 && <0.7'
  text: ! '>=1.2.2.2 && <1.3'
  vinyl: ! '>=0.5.3 && <0.12'
  lens: ! '>=4.15.4 && <4.18'
  swagger2: ! '>=2.1.6 && <2.5'
  template-haskell: ! '>=2.11.1.0 && <2.15'
all-versions:
- 0.5.4.0
- 0.5.5.0
- 0.6.0.0
- 0.6.1.0
author: Confer Health, Inc
latest: 0.6.1.0
description-type: haddock
description: Integration between Swagger and Vinyl/Frames records allowing easily
  derivable/explicit Swagger definitions for records.
license-name: BSD-3-Clause
