homepage: https://github.com/ConferHealth/composite#readme
changelog-type: ''
hash: 3dbc8b82b2fa1dbe2432b7fbf5e65cb3cabf33c64c11294453dfba35143bd782
test-bench-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  composite-swagger: -any
  base: ! '>=4.7 && <5'
  composite-base: -any
  hspec: -any
  text: ! '>=1.2.2.2 && <1.3'
  vinyl: ! '>=0.5.3 && <0.8'
  lens: ! '>=4.15.4 && <4.17'
  swagger2: ! '>=2.1.6 && <2.3'
  QuickCheck: -any
  composite-aeson: -any
  template-haskell: ! '>=2.11.1.0 && <2.13'
maintainer: oss@confer.health
synopsis: Swagger for Vinyl/Frames records
changelog: ''
basic-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  base: ! '>=4.7 && <5'
  composite-base: ! '>=0.5.3.0 && <0.6'
  text: ! '>=1.2.2.2 && <1.3'
  vinyl: ! '>=0.5.3 && <0.8'
  lens: ! '>=4.15.4 && <4.17'
  swagger2: ! '>=2.1.6 && <2.3'
  template-haskell: ! '>=2.11.1.0 && <2.13'
all-versions:
- '0.5.4.0'
author: Confer Health, Inc
latest: '0.5.4.0'
description-type: haddock
description: Integration between Swagger and Vinyl/Frames records allowing easily
  derivable/explicit Swagger definitions for records.
license-name: BSD3
