homepage: https://github.com/ConferHealth/composite#readme
changelog-type: ''
hash: 45e7b109393e4a181ad15fb98da87d131a3fe7a572a47dd91b85d6e946030cc4
test-bench-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  composite-swagger: -any
  base: ! '>=4.7 && <5'
  composite-base: -any
  hspec: -any
  text: ! '>=1.2.2.2 && <1.3'
  vinyl: ! '>=0.5.3 && <0.9'
  lens: ! '>=4.15.4 && <4.17'
  swagger2: ! '>=2.1.6 && <2.3'
  QuickCheck: -any
  composite-aeson: -any
  template-haskell: ! '>=2.11.1.0 && <2.14'
maintainer: oss@confer.health
synopsis: Swagger for Vinyl/Frames records
changelog: ''
basic-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  base: ! '>=4.7 && <5'
  composite-base: ! '>=0.5.3.0 && <0.6'
  text: ! '>=1.2.2.2 && <1.3'
  vinyl: ! '>=0.5.3 && <0.9'
  lens: ! '>=4.15.4 && <4.17'
  swagger2: ! '>=2.1.6 && <2.3'
  template-haskell: ! '>=2.11.1.0 && <2.14'
all-versions:
- '0.5.4.0'
- '0.5.5.0'
author: Confer Health, Inc
latest: '0.5.5.0'
description-type: haddock
description: Integration between Swagger and Vinyl/Frames records allowing easily
  derivable/explicit Swagger definitions for records.
license-name: BSD3
