homepage: https://github.com/ConferOpenSource/composite#readme
changelog-type: ''
hash: 7ee3300db2325a0ccfc89bd6d850195285467b979839657c377f718f6ddaad9e
test-bench-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  composite-swagger: -any
  base: ! '>=4.7 && <5'
  composite-base: -any
  hspec: -any
  text: ! '>=1.2.2.2 && <1.3'
  vinyl: ! '>=0.5.3 && <0.13'
  lens: ! '>=4.15.4 && <4.18'
  swagger2: ! '>=2.1.6 && <2.5'
  QuickCheck: -any
  composite-aeson: -any
  template-haskell: ! '>=2.11.1.0 && <2.15'
maintainer: oss@vitalbio.com
synopsis: Swagger for Vinyl records
changelog: ''
basic-deps:
  insert-ordered-containers: ! '>=0.2.1.0 && <0.3'
  base: ! '>=4.7 && <5'
  composite-base: ! '>=0.7 && <0.8'
  text: ! '>=1.2.2.2 && <1.3'
  vinyl: ! '>=0.5.3 && <0.13'
  lens: ! '>=4.15.4 && <4.18'
  swagger2: ! '>=2.1.6 && <2.5'
  template-haskell: ! '>=2.11.1.0 && <2.15'
all-versions:
- 0.5.4.0
- 0.5.5.0
- 0.6.0.0
- 0.6.1.0
- 0.6.2.0
- 0.7.0.0
- 0.7.1.0
author: Dan Fithian
latest: 0.7.1.0
description-type: haddock
description: Integration between Swagger and Vinyl records allowing easily derivable/explicit
  Swagger definitions for records.
license-name: BSD-3-Clause
