homepage: https://github.com/tel/Configurable
changelog-type: ''
hash: 3a9f11249effd61e6ce9de1a09d65951d69675e4dab2a6647a7a1b55cfe74960
test-bench-deps: {}
maintainer: Joseph Abrahamson <me@jspha.com>
synopsis: Declare types as Configurable then specialize them all in one place
changelog: ''
basic-deps:
  base: ==4.5.*
all-versions:
- 0.1.0.0
author: Joseph Abrahamson <me@jspha.com>
latest: 0.1.0.0
description-type: haddock
description: Declare types as Configurable then specialize them all in one place
license-name: MIT
