homepage: ''
changelog-type: ''
hash: 94c581dd010c73cb37c3cf9b79a1b542f2d2232355acf48891fa3a0f16727509
test-bench-deps:
  case-insensitive: ! '>=1.2.0.3 && <1.3'
  base: -any
  aeson-pretty: ! '>=0.7.2 && <0.8'
  unordered-containers: ! '>=0.2.5.1 && <0.3'
  hspec: ! '>=2.1.3 && <2.2'
  mtl: ! '>=2.1 && <2.3'
  pretty-show: ! '>=1.6.8 && <1.7'
  configifier: -any
  scientific: ! '>=0.3.3.5 && <0.4'
  QuickCheck: ! '>=2.7.6 && <2.9'
  hspec-discover: ! '>=2.1.3 && <2.2'
  string-conversions: ! '>=0.3.0.3 && <0.5'
  aeson: ! '>=0.8.0.2 && <0.9'
  vector: ! '>=0.10.12.2 && <0.11'
maintainer: Matthias Fischmann <mf@zerobuzz.net>
synopsis: parser for config files, shell variables, command line args.
changelog: ''
basic-deps:
  either: ! '>=4.3 && <4.5'
  bytestring: ==0.10.*
  case-insensitive: ! '>=1.2 && <1.3'
  base: ! '>=4.7 && <5'
  unordered-containers: ! '>=0.2 && <0.3'
  text: ! '>=1.2 && <1.3'
  containers: ! '>=0.5 && <0.6'
  functor-infix: ! '>=0.0.3 && <0.1'
  mtl: ! '>=2.1 && <2.3'
  pretty-show: ! '>=1.6.8 && <1.7'
  configifier: -any
  string-conversions: ! '>=0.3.0.3 && <0.5'
  template-haskell: ! '>=2.10 && <2.11'
  safe: ! '>=0.3 && <0.4'
  yaml: ==0.8.*
  vector: ! '>=0.10 && <0.12'
  directory: ! '>=1.2 && <1.3'
all-versions:
- 0.0.2
- 0.0.3
- 0.0.4
- 0.0.5
- 0.0.6
- 0.0.7
- 0.0.8
- 0.1.0
- 0.1.1
author: Matthias Fischmann <mf@zerobuzz.net>, Andres Löh <andres@well-typed.com>
latest: 0.1.1
description-type: haddock
description: See <https://github.com/zerobuzz/configifier/blob/master/README.md README>
license-name: AGPL-3.0-only
