homepage: ''
changelog-type: ''
hash: 78b84d7a4fcd58b06960277dfd89fc3e04f5b6bee815fde3b4bf00337182eb78
test-bench-deps: {}
maintainer: Timothy Hobbs <timothyhobbs@seznam.cz>
synopsis: A small program for swapping out dot files.
changelog: ''
basic-deps:
  unix: -any
  base: <5
  filepath: -any
  vty-menu: -any
  directory: -any
all-versions:
- 0.0.0
- 0.0.1
author: Timothy Hobbs
latest: 0.0.1
description-type: haddock
description: Manage multiple configuration profiles for the same program.  Swap out
  dot files quickly.
license-name: GPL-3.0-only
