homepage: ''
changelog-type: ''
hash: d6b5125d5ff73846e485fc75bdd9c49b25653ef49df0f73cd649a4d97647585f
test-bench-deps: {}
maintainer: nate@natesoares.com
synopsis: Parse config files
changelog: ''
basic-deps:
  MissingH: ! '>=1.0'
  Dangerous: ! '>=0.2.2'
  base: ! '>=4 && <5'
  parsec: ! '>=3.1'
  mtl: ! '>=1.1'
all-versions:
- '0.1'
author: Nate Soares
latest: '0.1'
description-type: haddock
description: Parses a config file into [(String, [(String, String)])]
license-name: MIT
