homepage: http://github.com/bos/configurator
changelog-type: ''
hash: a96d4c52b93a4a7d5909421853964a26f1153f32f8c4f11f9e04b249653e4034
test-bench-deps:
  test-framework-hunit: -any
  bytestring: -any
  test-framework: -any
  base: -any
  configurator: -any
  text: -any
  filepath: -any
  HUnit: -any
  directory: -any
maintainer: Bryan O'Sullivan <bos@serpentine.com>
synopsis: Configuration management
changelog: ''
basic-deps:
  bytestring: -any
  base: ==4.*
  unordered-containers: -any
  text: ! '>=0.11.1.0'
  unix-compat: -any
  hashable: -any
  attoparsec: ! '>=0.10.0.2'
  directory: -any
all-versions:
- 0.0.0.1
- 0.0.1.1
- 0.1.0.0
- 0.2.0.0
- 0.2.0.1
- 0.2.0.2
- 0.3.0.0
author: Bryan O'Sullivan <bos@serpentine.com>
latest: 0.3.0.0
description-type: markdown
description: ! "# Welcome to configurator\n\nThis is a library for configuring Haskell
  daemons and programs.\n\nIts features include:\n\n* Automatic, dynamic reloading
  in response to modifications to\n  configuration files.\n\n* A simple, but flexible,
  configuration language, supporting several\n  of the most commonly needed types
  of data, along with interpolation\n  of strings from the configuration or the system
  environment\n  (e.g. `$(HOME)`).\n\n* Subscription-based notification of changes
  to configuration\n  properties.\n\n* An `import` directive allows the configuration
  of a complex\n  application to be split across several smaller files, or\n  configuration
  data to be shared across several applications.\n\n# Configuration file format\n\nFor
  details of the configuration file format, see [the Haddock documentation](http://hackage.haskell.org/packages/archive/configurator/latest/doc/html/Data-Configurator.html).\n\n#
  Join in!\n\nWe are happy to receive bug reports, fixes, documentation enhancements,\nand
  other improvements.\n\nPlease report bugs via the\n[github issue tracker](http://github.com/bos/configurator/issues).\n\nMaster
  [git repository](http://github.com/bos/configurator):\n\n* `git clone git://github.com/bos/configurator.git`\n\nThere's
  also a [Mercurial mirror](http://bitbucket.org/bos/configurator):\n\n* `hg clone
  http://bitbucket.org/bos/configurator`\n\n(You can create and contribute changes
  using either git or Mercurial.)\n\nAuthors\n-------\n\nThis library is written and
  maintained by Bryan O'Sullivan,\n<bos@serpentine.com>.\n"
license-name: BSD-3-Clause
