homepage: ''
changelog-type: ''
hash: 522abf9d77c117e3598243974d7d4c71ad70a7867b7f26fd39b57421a9cfdc5d
test-bench-deps: {}
maintainer: konn.jinro_at_gmail.com
synopsis: Simple data type for application configuration.
changelog: ''
basic-deps:
  base: ! '>=4.0 && <5'
  containers: ! '>=0.3 && <0.6'
all-versions:
- '0.1'
- 0.1.1
author: Hiromi ISHII
latest: 0.1.1
description-type: haddock
description: Simple data type to store Typeable values.
license-name: BSD-3-Clause
