homepage: https://github.com/GaloisInc/config-value-getopt
changelog-type: markdown
hash: 4a6aae87335dfa22daf4c89724469396e5c62a13770f582845de7429f172bcac
test-bench-deps: {}
maintainer: emertens@galois.com
synopsis: Interface between config-value and System.GetOpt
changelog: |
  0.1.1.1
  -------
  * Support `config-value-0.7`

  0.1.1.0
  -------
  * Support `config-value-0.6`

  0.1.0.0
  -------

  * Initial release
basic-deps:
  base: ! '>=4.8 && <4.15'
  text: ! '>=1.2.1.3 && <1.3'
  config-value: ! '>=0.7 && <0.8'
all-versions:
- 0.1.0.0
- 0.1.1.0
- 0.1.1.1
author: Eric Mertens
latest: 0.1.1.1
description-type: markdown
description: |
  config-value-getopt
  ===================

  The config-value-getopt package allows GetOpt[1] specified options
  to be loaded from a configuration file in the config-value[2] format.

  * config-value section names are matched against the "long" option names
  in GetOpt.
  * Argument values can be provided as strings or numbers
  * An option will be omitted if its value is set to `no`
  * An option's argument will be omitted if its value is set to `yes`

  Example:

  ```
  address:       "::"
  port:          9000
  no-access-log: yes
  hostname:      no
  ```

  translates to

  ```
  --address="::" --port="9000" --no-access-log
  ```

  1. https://hackage.haskell.org/package/base-4.8.2.0/docs/System-Console-GetOpt.html
  2. https://hackage.haskell.org/package/config-value
license-name: MIT
