homepage: ''
changelog-type: ''
hash: 7289e34fd2b3612b8d21a0ccceeab8f59b9a52c3740ac775619ebd6458f1ff89
test-bench-deps: {}
maintainer: Ville Tirronen <ville.e.t.tirronen@jyu.fi>
synopsis: Template haskell for reading ConfigFiles.
changelog: ''
basic-deps:
  ConfigFile: ! '>=1.0.6 && <2'
  base: ! '>=4.3 && <5'
  parsec: ! '>=3.1.0 && <4'
  template-haskell: -any
all-versions:
- '0.1'
- '0.2'
author: Ville Tirronen
latest: '0.2'
description-type: haddock
description: ! 'This module provides syntax for concise definitions of config files
  from

  Data.ConfigFile through template haskell.

  For example, the following splice,

  $(genConf "Example" [$conf|

  elbow/center -> ec :: Double

  elbow/min    -> emi :: Double

  elbow/max    -> ema :: Double

  |])

  resolves into declaration of the following datatype

  data Example = Example {ec  :: Double

  ,emi :: Double

  ,ema :: Double}

  and a function

  loadExample :: (MonadIO m) => FilePath -> m (Either CPError Example) ,

  which uses Data.ConfigFile to read a values for the above struct from

  a file.'
license-name: LicenseRef-LGPL
