homepage: https://github.com/robx/configurator-pg
changelog-type: markdown
hash: fbb5daf2d0c4d223d91992e72743770b8d955790dc14d1a005ce151cd084b0bd
test-bench-deps:
  test-framework-hunit: ! '>=0.3.0.2 && <0.4'
  bytestring: ! '>=0.10.8.1 && <0.11'
  test-framework: ! '>=0.8.1.1 && <0.9'
  base: ! '>=4.9.1 && <4.13'
  text: ! '>=1.2.2.2 && <1.3'
  filepath: ! '>=1.4.1.1 && <1.5'
  protolude: ! '>=0.1.10 && <0.3'
  HUnit: ! '>=1.5 && <1.7'
  configurator-pg: -any
maintainer: rob@vllmrt.net
synopsis: Reduced parser for configurator-ng config files
changelog: |
  # Revision history for configurator-pg

  ## 0.1.0.0 -- 2019-06-03

  * First version.
basic-deps:
  base: ! '>=4.9.1 && <4.13'
  text: ! '>=1.2.2.2 && <1.3'
  protolude: ! '>=0.1.10 && <0.3'
  containers: ! '>=0.5.7.1 && <0.7'
  attoparsec: ! '>=0.13.1 && <0.14'
  scientific: ! '>=0.3.5.2 && <0.4'
all-versions:
- 0.1.0.0
author: Robert Vollmert
latest: 0.1.0.0
description-type: haddock
description: |-
  This module provides a simplified and updated interface to the
  configuration file format of
  <https://hackage.haskell.org/package/configurator configurator> and
  <https://hackage.haskell.org/package/configurator-ng configurator-ng>.
  Its aim is primarily to allow updating programs that depend on
  configurator-ng to new versions of GHC without changing the
  configuration file format.
license-name: BSD-3-Clause
