homepage: https://gitlab.com/guyonvarch/config-manager
changelog-type: ''
hash: 2a7332247885a4aab19823ebe4ab9c808067901b86d5b6da0810fcf97475299b
test-bench-deps:
  test-framework-hunit: -any
  test-framework: -any
  base: -any
  time: -any
  unordered-containers: -any
  text: -any
  HUnit: -any
  config-manager: -any
  temporary: -any
  directory: -any
maintainer: joris@guyonvarch.me
synopsis: Configuration management
changelog: ''
basic-deps:
  base: <5
  time: -any
  unordered-containers: -any
  text: -any
  filepath: -any
  parsec: -any
all-versions:
- 0.0.0.1
- 0.0.0.2
- 0.1.0.0
- 0.2.0.0
- 0.3.0.0
- 0.3.0.1
author: Joris Guyonvarch
latest: 0.3.0.1
description-type: haddock
description: ! 'A configuration management library which supports:


  * name-value bindings,


  * required or optional imports,


  * comments.


  For details of the configuration file format, see

  <http://hackage.haskell.org/packages/archive/config-manager/latest/doc/html/Data-ConfigManager.html>.'
license-name: GPL-3.0-only
