homepage: https://toktok.github.io/
changelog-type: ''
hash: b441f3a0f24afc43306c4adb9d6ecf5feb1958da4b0ef866bb8ca30db5c76755
test-bench-deps:
  base: <5
  hspec: -any
  groom: -any
  schema: -any
  msgpack-binary: -any
  QuickCheck: -any
maintainer: Iphigenia Df <iphydf@gmail.com>
synopsis: Encoding-independent schemas for Haskell data types.
changelog: ''
basic-deps:
  base: <5
all-versions:
- 0.0.1
- 0.0.2
author: Iphigenia Df <iphydf@gmail.com>
latest: 0.0.2
description-type: haddock
description: A Haskell implementation of encoding-independent schemas.
license-name: GPL-3.0-only
