homepage: https://toktok.github.io/
changelog-type: ''
hash: 0284e86913a8089ec96ea2d797d878cec33fab06b0c9adca8027d5654da40a15
test-bench-deps:
  base: <5
  hspec: -any
  schema: -any
  QuickCheck: -any
maintainer: Iphigenia Df <iphydf@gmail.com>
synopsis: Encoding-independent schemas for Haskell data types.
changelog: ''
basic-deps:
  base: <5
all-versions:
- 0.0.1
author: Iphigenia Df <iphydf@gmail.com>
latest: 0.0.1
description-type: haddock
description: A Haskell implementation of encoding-independent schemas.
license-name: AGPL-3.0-only
