homepage: https://github.com/fgaz/SConfig
changelog-type: ''
hash: 1505b270fa54a75835430111a148007d5b11e66e8c6d3fcebed9620426d8a214
test-bench-deps: {}
maintainer: fgaz@users.noreply.github.com
synopsis: A simple config library
changelog: ''
basic-deps:
  base: ==4.*
  containers: ! '>=0.5 && <1'
all-versions:
- 0.1.0.0
- 0.2.0.0
author: Francesco Gazzetta
latest: 0.2.0.0
description-type: haddock
description: A simple config library.
license-name: MIT
