homepage: https://github.com/koterpillar/simpleconfig#readme
changelog-type: ''
hash: 31214c4d628d1017d4b05bde57e7944d6773e866d60bc7f3f6ff88ff81145d14
test-bench-deps:
  base: -any
  text: -any
  generic-deriving: -any
  containers: -any
  simpleconfig: -any
  lens: -any
maintainer: a@koterpillar.com
synopsis: Short description of your package
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  containers: -any
  lens: -any
all-versions:
- '0.0.1'
author: Alexey Kotlyarov
latest: '0.0.1'
description-type: markdown
description: ! '# simpleconfig


  ### Releasing


  * Install [bumpversion](https://github.com/peritus/bumpversion): `pip install bumpversion`.

  * Run `bumpversion major|minor|patch`.

  * Run `git push --tags`.

'
license-name: BSD3
