homepage: https://github.com/koterpillar/simpleconfig#readme
changelog-type: ''
hash: 1088a81fe8c2aee70afcdb3db1f4a05b970feddcd5dcf863c1a499b4ff24c28b
test-bench-deps:
  base: -any
  text: -any
  generic-deriving: -any
  containers: -any
  simpleconfig: -any
  lens: -any
maintainer: a@koterpillar.com
synopsis: Short description of your package
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  containers: -any
  lens: -any
all-versions:
- '0.0.1'
- '0.0.5'
- '0.0.7'
author: Alexey Kotlyarov
latest: '0.0.7'
description-type: markdown
description: ! '# simpleconfig


  ### Releasing


  * Install [bumpversion](https://github.com/peritus/bumpversion): `pip install bumpversion`.

  * Run `bumpversion major|minor|patch`.

  * Run `git push --tags && git push`.

'
license-name: BSD3
