homepage: https://github.com/yunomu/simple-config
changelog-type: ''
hash: f191b12a5aa3d8caa4e60d573376fb3c5645fc81e062baac6b58cfa155c5eae6
test-bench-deps:
  base: ! '>=4 && <5'
  hspec: -any
maintainer: yunomu@gmail.com
synopsis: Simple config file parser generator
changelog: ''
basic-deps:
  bytestring: -any
  base: ! '>=4 && <5'
  parsec: -any
  data-default: -any
  network-uri: ! '>=2.6'
  transformers: -any
  template-haskell: -any
all-versions:
- 1.0.0
- 1.1.0
- 1.1.1.0
- 1.2.0
- 1.2.1
- 1.2.2
- 1.2.2.1
author: YusukeNomura
latest: 1.2.2.1
description-type: haddock
description: Simple config file parser generator
license-name: BSD-3-Clause
