homepage: https://github.com/koterpillar/simpleconfig#readme
changelog-type: ''
hash: 48debab035555c1a26f7aa7a9df8b62f5e09b6e6b641607b00932ba8f7f080bb
test-bench-deps:
  either: -any
  base: -any
  hspec: -any
  text: -any
  generic-deriving: -any
  containers: -any
  simpleconfig: -any
  lens: -any
maintainer: a@koterpillar.com
synopsis: Short description of your package
changelog: ''
basic-deps:
  either: -any
  base: ! '>=4.7 && <5'
  containers: -any
  lens: -any
all-versions:
- 0.0.1
- 0.0.5
- 0.0.7
- 0.0.8
- 0.0.9
- 0.0.10
author: Alexey Kotlyarov
latest: 0.0.10
description-type: markdown
description: ! '# simpleconfig


  ### Releasing


  * Install [bumpversion](https://github.com/peritus/bumpversion): `pip install bumpversion`.

  * Run `bumpversion major|minor|patch`.

  * Run `git push --tags && git push`.

'
license-name: BSD-3-Clause
