homepage: https://github.com/koterpillar/simpleconfig#readme
changelog-type: ''
hash: 806a764727eed0c6e341fc18cf31efe169ff9fd98b2a0d903d662be7836ac454
test-bench-deps:
  base: -any
  text: -any
  generic-deriving: -any
  containers: -any
  simpleconfig: -any
  lens: -any
maintainer: a@koterpillar.com
synopsis: Short description of your package
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  containers: -any
  lens: -any
all-versions:
- '0.0.1'
- '0.0.5'
author: Alexey Kotlyarov
latest: '0.0.5'
description-type: markdown
description: ! '# simpleconfig


  ### Releasing


  * Install [bumpversion](https://github.com/peritus/bumpversion): `pip install bumpversion`.

  * Run `bumpversion major|minor|patch`.

  * Run `git push --tags && git push`.

'
license-name: BSD3
