homepage: https://github.com/koterpillar/simpleconfig#readme
changelog-type: ''
hash: fcf4539ce2bbb0d13788dd29f4179fe65378bdaefa57242d0324cb2ec03c7418
test-bench-deps:
  base: -any
  text: -any
  generic-deriving: -any
  containers: -any
  simpleconfig: -any
  lens: -any
maintainer: a@koterpillar.com
synopsis: Short description of your package
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  containers: -any
  lens: -any
all-versions:
- '0.0.1'
- '0.0.5'
- '0.0.7'
- '0.0.8'
author: Alexey Kotlyarov
latest: '0.0.8'
description-type: markdown
description: ! '# simpleconfig


  ### Releasing


  * Install [bumpversion](https://github.com/peritus/bumpversion): `pip install bumpversion`.

  * Run `bumpversion major|minor|patch`.

  * Run `git push --tags && git push`.

'
license-name: BSD3
