homepage: https://github.com/martyall/servant-zeppelin#readme
changelog-type: ''
hash: 1ebc4e4c2a3b2059215a414a66b98f4b8454fd4b622b00fbd338c34ef909f7ba
test-bench-deps:
  insert-ordered-containers: -any
  servant-zeppelin-swagger: -any
  base: -any
  hspec: -any
  servant-swagger: -any
  servant: -any
  containers: -any
  lens: -any
  servant-zeppelin: -any
  swagger2: -any
  aeson: -any
maintainer: martin[dot]allen26[at]gmail.com
synopsis: Swagger instances for servant-zeppelin combinators.
changelog: ''
basic-deps:
  insert-ordered-containers: -any
  base: ! '>=4.7 && <5'
  text: ==1.2.*
  servant-swagger: ! '>=1.1.2.1'
  servant: ! '>=0.10 && <0.12'
  singletons: ! '>=2.2 && <2.3'
  lens: -any
  servant-zeppelin: ! '>=0.1 && <0.2'
  swagger2: ! '>=2.1 && <2.2'
  aeson: ! '>=0.7 && <1.3'
all-versions:
- 0.1.0.0
- 0.1.0.2
- 0.1.0.3
author: Martin Allen, Ben Weitzman
latest: 0.1.0.3
description-type: markdown
description: ! '# servant-side-loaded

'
license-name: BSD-3-Clause
