homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: markdown
hash: ce381fadec710e147ca19e87e437b4b823a3083afedf4efbd8ab250a7ba426dc
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: Servant swagger ui
changelog: |
  - 0.3.2.3.19.3
      - Update to `swagger-ui-3.19.3`
      - Add GHC-8.6 support
      - Drop `servant<0.14` support

  - 0.3.0.3.13.2
      - Update to `swagger-ui-3.13.2`
      - Split package into multiple packages:
          - [`servant-swagger-ui-core`](http://hackage.haskell.org/package/servant-swagger-ui-core)
          - [`servant-swagger-ui-redoc`](http://hackage.haskell.org/package/servant-swagger-ui-redoc)
          - [`servant-swagger-ui-jensoleg`](http://hackage.haskell.org/package/servant-swagger-ui-jensoleg)

  - 0.2.5.3.9.1
      - Support `servant-0.13`
      - Update to `swagger-ui-3.9.1`

  - 0.2.4.3.4.0
      - Update to `swagger-ui-3.4.0`

  - 0.2.4.3.0.20
      - Update to `swagger-ui-3.0.20`

  - 0.2.3.2.2.8
      - Support `servant-0.11`

  - 0.2.2.2.2.8
      - Support `servant-0.10`

  - 0.2.1.2.2.8
      - Update to `swagger-ui-2.2.8`
      - Add support for [jensoleg](https://github.com/jensoleg/swagger-ui>) theme

  - 0.2.0.2.1.5

      - Introduce `SwaggerSchemaUI`, this fixes
        [Swagger UI does not work when nested](https://github.com/phadej/servant-swagger-ui/issues/8) issue
        by sacrificing some subjective flexibility.
      - update bundled swagger-ui to version 2.1.5

  - 0.1.1.2.1.4

      - Documentation and example improvements
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  file-embed-lzma: ! '>=0 && <0.1'
  base: ! '>=4.7 && <4.13'
  text: ! '>=1.2.3.0 && <1.3'
  servant-server: ! '>=0.14 && <0.17'
  servant-swagger-ui-core: ! '>=0.3 && <0.4'
  servant: ! '>=0.14 && <0.17'
  swagger2: ! '>=2.3.0.1 && <2.4'
all-versions:
- 0.1.0.2.1.4
- 0.1.1.2.1.4
- 0.2.0.2.1.5
- 0.2.1.2.2.8
- 0.2.2.2.2.8
- 0.2.3.2.2.8
- 0.2.4.3.0.20
- 0.2.4.3.4.0
- 0.2.5.3.9.1
- 0.3.0.3.13.2
- 0.3.2.3.19.3
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: 0.3.2.3.19.3
description-type: haddock
description: |-
  Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)

  https://github.com/swagger-api/swagger-ui
license-name: BSD-3-Clause
