homepage: http://github.com/haskell-servant/servant-auth#readme
changelog-type: markdown
hash: a79a1820e5c74e59ef7f8e905e2c2a9564e8aadd699b837eca26be83b4c620ef
test-bench-deps:
  base: -any
  hspec: ! '>2 && <3'
  text: -any
  servant-auth-swagger: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: -any
  swagger2: -any
  QuickCheck: ! '>=2.8 && <2.14'
maintainer: jkarni@gmail.com
synopsis: servant-swagger/servant-auth compatibility
changelog: |
  # Changelog

  All notable changes to this project will be documented in this file.

  The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
  and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.html).

  ## [Unreleased]

  ## [0.2.10.0] - 2018-06-18

  ### Added
  - Support for GHC 8.4 by @phadej
  - Changelog by @domenkozar
  - #93: add Cookie in SwaggerSpec API by @domenkozar
  - #42: add dummy AllHasSecurity Cookie instance by @sordina
basic-deps:
  base: ! '>=4.8 && <4.13'
  text: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: ==0.3.*
  swagger2: ! '>=2 && <3'
all-versions:
- 0.2.6.0
- 0.2.6.1
- 0.2.7.0
- 0.2.8.0
- 0.2.9.0
- 0.2.10.0
author: Julian K. Arni
latest: 0.2.10.0
description-type: haddock
description: |-
  This package provides instances that allow generating swagger2 schemas from
  <https://hackage.haskell.org/package/servant servant>
  APIs that use
  <https://hackage.haskell.org/package/servant-auth servant-auth's> @Auth@ combinator.

  For a quick overview of the usage, see the <http://github.com/haskell-servant/servant-auth#readme README>.
license-name: BSD-3-Clause
