homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: markdown
hash: 61199182dc35865413150357514bfccf97b266225dd3af2b31c736b7bff4e582
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: Servant swagger ui core components
changelog: ! '# 0.3.1


  - Support `servant-0.14`

'
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  base: ! '>=4.7 && <4.12'
  blaze-markup: ! '>=0.7.0.2 && <0.9'
  text: ! '>=1.2.0.6 && <1.3'
  servant-server: ! '>=0.4.4.5 && <0.15'
  servant: ! '>=0.5 && <0.15'
  servant-blaze: ! '>=0.4.4.5 && <0.9'
  swagger2: ! '>=2.0.1 && <2.4'
  transformers: ! '>=0.3 && <0.6'
  wai-app-static: ! '>=3.0.1.1 && <3.2'
  http-media: ! '>=0.6.2 && <0.8'
  transformers-compat: ! '>=0.3 && <0.7'
all-versions:
- '0.3'
- '0.3.1'
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: '0.3.1'
description-type: haddock
description: ! 'Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)


  See servant-swagger-ui, servant-swagger-ui-jensoleg or

  servant-swagger-ui-redoc for "concrete" implementations.'
license-name: BSD3
