homepage: https://github.com/phadej/servant-swagger-ui
changelog-type: ''
hash: 22f22c1263107614498e69d91081e76e427a496702c476a28be89323ffb33f5d
test-bench-deps: {}
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
synopsis: ! 'Servant swagger ui: ReDoc theme'
changelog: ''
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  file-embed-lzma: ! '>=0 && <0.1'
  base: ! '>=4.7 && <4.12'
  text: ! '>=1.2.0.6 && <1.3'
  servant-server: ! '>=0.4.4.5 && <0.14'
  servant-swagger-ui-core: ! '>=0.3 && <0.4'
  servant: ! '>=0.4.4.5 && <0.14'
  swagger2: ! '>=2.0.1 && <2.3'
all-versions:
- '0.3.0.1.21.2'
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: '0.3.0.1.21.2'
description-type: haddock
description: ! 'Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)


  ReDoc theme: https://github.com/Rebilly/ReDoc'
license-name: BSD3
