homepage: http://github.com/haskell-servant/servant-auth#readme
changelog-type: ''
hash: b66a3062ebc0306070a990d7853e6a4e3d577828862abf5913c3bcff687ea23b
test-bench-deps:
  base: -any
  hspec: ! '>2 && <3'
  text: -any
  servant-auth-swagger: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: -any
  swagger2: -any
  QuickCheck: ! '>=2.8 && <2.12'
maintainer: jkarni@gmail.com
synopsis: servant-swagger/servant-auth compatibility
changelog: ''
basic-deps:
  base: ! '>=4.8 && <4.11'
  text: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: ==0.3.*
  swagger2: ! '>=2 && <3'
all-versions:
- '0.2.6.0'
- '0.2.6.1'
- '0.2.7.0'
- '0.2.8.0'
- '0.2.9.0'
author: Julian K. Arni
latest: '0.2.9.0'
description-type: haddock
description: ! 'This package provides instances that allow generating swagger2 schemas
  from

  <https://hackage.haskell.org/package/servant servant>

  APIs that use

  <https://hackage.haskell.org/package/servant-auth servant-auth''s> @Auth@ combinator.


  For a quick overview of the usage, see the <http://github.com/haskell-servant/servant-auth#readme
  README>.'
license-name: BSD3
