homepage: http://github.com/plow-technologies/servant-auth#readme
changelog-type: ''
hash: 5f5e76064b193d886417f4a1f2c06d4a9e7e76f75e986bf71d0513eced811040
test-bench-deps:
  base: -any
  hspec: ! '>2 && <3'
  text: -any
  servant-auth-swagger: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: -any
  swagger2: -any
  QuickCheck: ! '>=2.8 && <2.11'
maintainer: jkarni@gmail.com
synopsis: servant-swagger/servant-auth compatibility
changelog: ''
basic-deps:
  base: ! '>=4.8 && <4.11'
  text: -any
  servant-swagger: -any
  servant: -any
  lens: -any
  servant-auth: ==0.3.*
  swagger2: ! '>=2 && <3'
all-versions:
- '0.2.6.0'
- '0.2.6.1'
- '0.2.7.0'
- '0.2.8.0'
author: Julian K. Arni
latest: '0.2.8.0'
description-type: haddock
description: Please see README.md
license-name: BSD3
