homepage: https://github.com/nakaji-dayo/servant-swagger-tags#readme
changelog-type: ''
hash: 2d743e9ad1cfcca537acc99e0b97e0e4feda3b5c842937dbf5895261e3105bf1
test-bench-deps: {}
maintainer: nakaji.dayo@mail.com
synopsis: Swagger Tags for Servant
changelog: ''
basic-deps:
  insert-ordered-containers: -any
  base: '>=4.7 && <5'
  text: -any
  servant-swagger: -any
  servant-mock: -any
  servant-server: -any
  servant: -any
  lens: -any
  swagger2: -any
all-versions:
- 0.1.0.0
- 0.1.0.1
author: Daishi Nakajima
latest: 0.1.0.1
description-type: markdown
description: |
  # servant-swagger-tags
license-name: BSD-3-Clause
