homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: markdown
hash: 6c371c01ec9ccb58b12db77695c7055fda63b22e0feec8359c9e7152dab6dd0b
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: Servant swagger ui core components
changelog: |
  # 0.3.2

  - Support GHC-8.6.
  - Drop servant <0.14 support

  # 0.3.1

  - Support `servant-0.14`
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  base: ! '>=4.7 && <4.13'
  blaze-markup: ! '>=0.7.0.2 && <0.9'
  text: ! '>=1.2.3.0 && <1.3'
  servant-server: ! '>=0.14 && <0.16'
  servant: ! '>=0.14 && <0.16'
  servant-blaze: ! '>=0.8 && <0.10'
  swagger2: ! '>=2.3.0.1 && <2.4'
  transformers: ! '>=0.3 && <0.6'
  wai-app-static: ! '>=3.0.1.1 && <3.2'
  http-media: ! '>=0.7.1.3 && <0.8'
  transformers-compat: ! '>=0.3 && <0.7'
all-versions:
- '0.3'
- 0.3.1
- 0.3.2
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: 0.3.2
description-type: haddock
description: |-
  Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)

  See servant-swagger-ui, servant-swagger-ui-jensoleg or
  servant-swagger-ui-redoc for "concrete" implementations.
license-name: BSD-3-Clause
