homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: ''
hash: e2b59a65f0d4f8aa7e43881e0f5447c496908aff7b80dd9a3a9e1e825eb007a6
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: 'Servant swagger ui: Jens-Ole Graulund theme'
changelog: ''
basic-deps:
  bytestring: '>=0.10.4.0 && <0.11'
  file-embed-lzma: '>=0 && <0.1'
  base: '>=4.7 && <4.15'
  text: '>=1.2.3.0 && <1.3'
  servant-server: '>=0.14 && <0.19'
  servant-swagger-ui-core: '>=0.3.3 && <0.4'
  servant: '>=0.14 && <0.19'
  swagger2: '>=2.3.0.1 && <2.7'
all-versions:
- '0.3'
- 0.3.2
- 0.3.3
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: 0.3.3
description-type: haddock
description: |-
  Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)

  Jsn-Ole Graulund theme https://github.com/jensoleg/swagger-org
license-name: BSD-3-Clause
