homepage: https://github.com/haskell-servant/servant-swagger-ui
changelog-type: ''
hash: 08de4712ce33e92db87537ebe75e8a2e7691264139a3738a4d662b94079ca62a
test-bench-deps: {}
maintainer: haskell-servant-maintainers@googlegroups.com
synopsis: ! 'Servant swagger ui: ReDoc theme'
changelog: ''
basic-deps:
  bytestring: ! '>=0.10.4.0 && <0.11'
  file-embed-lzma: ! '>=0 && <0.1'
  base: ! '>=4.7 && <4.12'
  text: ! '>=1.2.0.6 && <1.3'
  servant-server: ! '>=0.4.4.5 && <0.15'
  servant-swagger-ui-core: ! '>=0.3 && <0.4'
  servant: ! '>=0.4.4.5 && <0.15'
  swagger2: ! '>=2.0.1 && <2.4'
all-versions:
- '0.3.0.1.21.2'
author: Oleg Grenrus <oleg.grenrus@iki.fi>
latest: '0.3.0.1.21.2'
description-type: haddock
description: ! 'Provide embedded swagger UI for servant and swagger (i.e. servant-swagger)


  ReDoc theme: https://github.com/Rebilly/ReDoc'
license-name: BSD3
