homepage: https://github.com/seanhess/services#readme
changelog-type: ''
hash: 695e61878895ffd38b9f75886317aa8dd3d725f786f719bf5866a27a0be5cdf1
test-bench-deps:
  base: -any
  tasty-hunit: -any
  tasty: -any
  services: -any
maintainer: seanhess@gmail.com
synopsis: Tools for building services
changelog: ''
basic-deps:
  bytestring: -any
  wai: -any
  base: ! '>=4.7 && <5'
  text: -any
  containers: -any
  binary: -any
  monad-logger: -any
  http-types: -any
  aeson: -any
all-versions:
- 0.2.0
author: Sean Hess
latest: 0.2.0
description-type: markdown
description: ! '# services

'
license-name: BSD-3-Clause
