homepage: https://github.com/nakaji-dayo/servant-swagger-tags#readme
changelog-type: ''
hash: ffd61b869e56a7543f0641fe017647cf05fb57a76cb2d2acd045fc47bfbafb07
test-bench-deps: {}
maintainer: nakaji.dayo@mail.com
synopsis: Swagger Tags for Servant
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  text: -any
  servant-swagger: -any
  servant-mock: -any
  servant-server: -any
  servant: -any
  containers: -any
  lens: -any
  swagger2: -any
all-versions:
- 0.1.0.0
author: Daishi Nakajima
latest: 0.1.0.0
description-type: markdown
description: |
  # servant-swagger-tags
license-name: BSD-3-Clause
