homepage: http://rel4tion.org/projects/settings/
changelog-type: text
hash: 85460baadca6d73bfde5dbc7ffab57c967a7bf626fec951f1a26b0fa6cb1a43a
test-bench-deps: {}
maintainer: fr33domlover@riseup.net
synopsis: Runtime-editable program settings.
changelog: ! "The changes are recorded by the version control system, Darcs. To see
  a log\nquickly from the terminal, run:\n\n  $ darcs changes --repo http://dev.rel4tion.org/fr33domlover/settings\n\nThere
  is also a web interface at <http://dev.rel4tion.org> which, among other\nthings,
  can display the history log.\n\nTo see the log in a local clone, first get a copy
  of the repository if you\nhaven't yet:\n\n  $ darcs get http://dev.rel4tion.org/fr33domlover/settings\n\nThen
  move into the newly created directory and run darcs:\n\n  $ cd settings\n  $ darcs
  changes\n"
basic-deps:
  base: ! '>=4.7 && <5'
  unordered-containers: ! '>=0.2.5'
  text: ! '>=1'
all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.2.0.0
- 0.2.1.0
- 0.2.2.0
- 0.3.0.0
author: fr33domlover
latest: 0.3.0.0
description-type: markdown
description: ! 'See the .cabal file for more info and link to project website the
  version

  control.


  The official download location is Hackage:


  <http://hackage.haskell.org/package/settings>


  This library is free software, and is committed to software freedom. It is

  released to the public domain using the CC0 Public Domain Dedication. For the

  boring "legal" details see the file ''COPYING''.


  See the file ''INSTALL'' for hints on installation. The file ''ChangeLog'' explains

  how to see the history log of the changes done in the code. ''NEWS'' provides a

  friendly overview of the changes for each release.

'
license-name: LicenseRef-PublicDomain
