homepage: https://github.com/louispan/l10n#readme
changelog-type: ''
hash: 5cb7306e08db141b55d410a18727a5a8a49d13e6e118998de32c93c8e7af5889
test-bench-deps: {}
maintainer: louis@pan.me
synopsis: Enables providing localization as typeclass instances in separate files.
changelog: ''
basic-deps:
  base: <6
  time: ! '>=1.5 && <2'
  text: ! '>=1 && <2'
all-versions:
- 0.1.0.1
author: Louis Pan
latest: 0.1.0.1
description-type: markdown
description: ! '[![Hackage](https://img.shields.io/hackage/v/l10n.svg)](https://hackage.haskell.org/package/l10n)

  [![Build Status](https://secure.travis-ci.org/louispan/l10n.png?branch=master)](http://travis-ci.org/louispan/l10n)


  A flexible of allowing localization via typeclass instances.

  This has benefits of providing translations in separate files (one file per locale).

  This also allow providing translations for new types without chaning existing code,
  by implementing the typeclass instance where the new types are defined.'
license-name: BSD-3-Clause
