homepage: https://github.com/agrafix/highjson
changelog-type: ''
hash: 5b8325f356872a24217a92dee2941a6a3972f8de77dfe26a052c924ab1cdda42
test-bench-deps:
  bytestring: -any
  base: -any
  hspec: ! '>=2.0'
  text: -any
  lens: -any
  swagger2: -any
  QuickCheck: ! '>=2.8'
  highjson: -any
  aeson: -any
  highjson-swagger: -any
maintainer: Alexander Thiemann <mail@athiemann.net>
synopsis: Derive swagger instances from highjson specs
changelog: ''
basic-deps:
  insert-ordered-containers: ! '>=0.2'
  base: ! '>=4.8 && <5'
  text: -any
  hvect: ! '>=0.4'
  lens: -any
  swagger2: ! '>=2.1.3'
  highjson: ! '>=0.4'
all-versions:
- 0.3.0.0
- 0.4.0.0
author: Alexander Thiemann <mail@athiemann.net>
latest: 0.4.0.0
description-type: haddock
description: Derive swagger instances from highjson specs
license-name: MIT
