homepage: https://en.wikipedia.org/wiki/Stack_(abstract_data_type)
changelog-type: ''
hash: a6750dc4e541b6e1a1ac3d5e5c4e4a607164e656ee1d60959fd162e287e23cd4
test-bench-deps: {}
maintainer: rwlock404@yahoo.com
synopsis: Stack data structure
changelog: ''
basic-deps:
  stm: ! '>=2.5.0.0 && <2.6'
  base: ! '>=4.7 && <5'
  nats: ! '>=1.1.2 && <1.2'
  deepseq: ! '>=1.4.4.0 && <1.5'
all-versions:
- 0.1.0
- 0.2.0
- 0.3.0
- 0.3.1
- 0.3.2
- 0.4.0
author: Robert Walker
latest: 0.4.0
description-type: haddock
description: |-
  A stack is a basic data structure that can be logically thought as linear structure represented by a real physical stack or pile, a structure where insertion and deletion of items takes place at one end called top of the stack.

  <<https://upload.wikimedia.org/wikipedia/commons/b/b4/Lifo_stack.png>>
license-name: BSD-3-Clause
