homepage: https://github.com/akaspin/global-config
changelog-type: ''
hash: 967e57ee6a69bb5382395f6cf1bc1e423efccd5bc080b80c1f84826ed305fbb7
test-bench-deps:
  global-config: -any
  test-framework-hunit: -any
  bytestring: -any
  test-framework: ! '>=0.4.1'
  base: ! '>=4 && <5'
  test-framework-quickcheck2: -any
  data-default: -any
  HUnit: ! '>=1.2 && <2'
  transformers: ! '>=0.2'
  QuickCheck: ! '>=2.4'
maintainer: Alexander Dorofeev <aka.spin@gmail.com>
synopsis: Global mutable configuration
changelog: ''
basic-deps:
  base: ! '>=4 && <5'
  global-variables: -any
  data-default: -any
  transformers: ! '>=0.2'
all-versions:
- 0.1.0
- 0.2.0
- 0.2.1
- 0.3.0
- 0.3.1
author: Alexander Dorofeev <aka.spin@gmail.com>spin
latest: 0.3.1
description-type: haddock
description: ! '@Data.Global.Config@ provides brain-free pattern to work with global

  configurations. Use wisely.'
license-name: BSD-3-Clause
