homepage: https://github.com/peddie/libconfig-haskell
changelog-type: ''
hash: b66b8d551dd5aa9b201efea671dbb8e3ec69451b370e0655e9ff9befa469b27e
test-bench-deps:
  base: -any
  doctest: ! '>=0.9.9'
  lens: ! '>=4.7'
  libconfig: -any
  doctest-prop: ! '>=0.2'
maintainer: mpeddie@gmail.com
synopsis: Haskell bindings to libconfig
changelog: ''
basic-deps:
  cereal-text: ! '>=0.1'
  cereal: ! '>=0.4 && <0.5'
  text-binary: ! '>=0.1'
  base: ! '>=4.6 && <4.9'
  text: ! '>=1.1 && <1.3'
  binary: ! '>=0.5 && <0.8'
  hashable: ! '>=1.2 && <1.3'
  transformers: ! '>=0.3'
  deepseq: ! '>=1.3'
  transformers-compat: ! '>=0.3'
  profunctors: ! '>=4 && <5'
all-versions:
- 0.1.0.0
- 0.2.0.0
- 0.3.0.0
author: Matthew Peddie
latest: 0.3.0.0
description-type: haddock
description: ! 'Low-level FFI bindings to the <http://www.hyperrealm.com/libconfig/
  libconfig>

  configuration file library.


  This library only binds to version 1.4.9 of the libconfig

  library, which is known as @libconfig9@ in Debian-like

  distributions, including Ubuntu.  It will not work with

  older versions of libconfig, including the @libconfig8@

  distributed in Ubuntu 12.04.


  See below for several flags you can use to reduce

  dependencies if this is a problem for you.  If you disable

  everything, this package will only depend on

  @transformers@, @text@, @hashable@ and @deepseq@.'
license-name: BSD-3-Clause
