homepage: ''
changelog-type: ''
hash: 71986e8dadf211a98ccfe9ba188e1db099dc7a5d993c9f4bf273d267ddaa2a58
test-bench-deps: {}
maintainer: Anchor Engineering <engineering@anchor.com.au>
synopsis: Methods to manipulate Configurator objects for Snap & Snaplets
changelog: ''
basic-deps:
  base: ! '>=4.7 && <4.8'
  configurator: -any
  unordered-containers: -any
  text: -any
all-versions:
- 0.1.0.0
author: Geoffrey Roberts <geoffrey.roberts@anchor.com.au>
latest: 0.1.0.0
description-type: haddock
description: Methods to manipulate Configurator objects for Snap & Snaplets
license-name: BSD-3-Clause
