homepage: ''
changelog-type: ''
hash: d18033468e77c6c0890b25711121e3145cb1673dcbd0fca29708f5b0d2370ecd
test-bench-deps: {}
maintainer: ciemniewski.kamil@gmail.com
synopsis: DEPRECATED! You should use standard Snap >= 0.9 "environments" functionality.
  It provided ability to easly read configuration based on given app environment given
  at command line, envs are defined in app configuration file
changelog: ''
basic-deps:
  snap: ==0.7.*
  base: ! '>=4 && <5'
  configurator: ! '>=0.2 && <0.3'
  unordered-containers: ! '>=0.1.4.3 && <0.2'
  text: ! '>=0.11 && <0.12'
  regex-tdfa: ! '>=1.1.8 && <1.2'
  snap-core: ==0.7.*
  mtl: ! '>=2 && <3'
  bson: ==0.1.6
all-versions:
- '0.1'
- 0.1.1
author: Kamil Ciemniewski
latest: 0.1.1
description-type: haddock
description: ''
license-name: BSD-3-Clause
