homepage: ''
changelog-type: ''
hash: 005d4eb75c09bc6ef55a45654524f5bcf898e7b0222bc87aa4b0f52956147db1
test-bench-deps: {}
maintainer: ajnsit@gmail.com
synopsis: Typesafe URLs for Snap applications.
changelog: ''
basic-deps:
  snap: -any
  bytestring: -any
  base: ! '>=4.7 && <4.9'
  text: -any
  filepath: -any
  path-pieces: -any
  containers: -any
  blaze-builder: -any
  mime-types: -any
  random: -any
  http-types: -any
  template-haskell: -any
all-versions:
- 0.0.1
author: Anupam Jain
latest: 0.0.1
description-type: markdown
description: ! "Snap-Routes\n===========\n\nSnap-routes provides typesafe routing
  for snap applications.\n\nFeatures\n========\n\nSnap-routes adds the following features
  on top of Snap -\n\n  - Typesafe URLs, including automatic boilerplate generation
  using TH. Including features such as -\n    - Nested Routes\n    - Subsites\n    -
  Route Annotations\n  - Seamlessly mix and match \"unrouted\" request handlers with
  typesafe routing.\n  - Sitewide Master data which is passed to all handlers and
  can be used for persistent data (like DB connections)\n\n\nChangelog\n=========\n\n*
  0.0.1   : Intial release\n"
license-name: MIT
