homepage: http://www.keera.es/blog/community/
changelog-type: ''
hash: 379901edb0c80acbcd90655efbf2164b8660119a0072e4fae50e0c4be2b1d260
test-bench-deps: {}
maintainer: ivan.perez@keera.es
synopsis: Haskell on Gtk rails - Gtk-based global environment for MVC applications
changelog: ''
basic-deps:
  base: ! '>=4 && <5'
  keera-hails-mvc-view: -any
  keera-hails-mvc-view-gtk: -any
  keera-hails-mvc-model-protectedmodel: -any
all-versions:
- 0.0.3.3
author: Ivan Perez
latest: 0.0.3.3
description-type: haddock
description: ''
license-name: BSD-3-Clause
