homepage: http://www.keera.co.uk/blog/community/
changelog-type: ''
hash: 2458fba521f383ea4401a05fc99b9d9f12c10d7f096abe38a9713366339f929a
test-bench-deps: {}
maintainer: support@keera.co.uk
synopsis: Haskell on Gtk rails - Gtk-based global environment for MVC applications
changelog: ''
basic-deps:
  base: '>=4 && <5'
  keera-hails-mvc-view: -any
  keera-hails-mvc-view-gtk: -any
  keera-hails-mvc-model-protectedmodel: -any
all-versions:
- 0.0.3.3
- 0.5.0
- 0.6.0
- 0.7.0
author: Ivan Perez
latest: 0.7.0
description-type: haddock
description: |-
  Keera Hails is a rapid application development system.

  The idea behind Hails is that you should be able to build cross platform
  applications with minimal effort, very quickly, and the result should be easy
  to maintain.

  This package defines an environment that combines a model and a view, where
  the latter is implemented using GTK+. Users of this package can install
  additional conditions that keep both in sync using keera-hails-reactivevalues
  to define such conditions.
license-name: BSD-3-Clause
