homepage: http://www.keera.es/blog/community/
changelog-type: ''
hash: 5a681949b7c30f1e3571c94da40a8623d23b74872dd60714b1c88636f60ee053
test-bench-deps: {}
maintainer: ivan.perez@keera.es
synopsis: Haskell on Gtk rails - Easy handling of configuration files
changelog: ''
basic-deps:
  base: ! '>=4 && <5'
  filepath: -any
  MissingK: -any
  directory: -any
all-versions:
- 0.0.3.3
author: Ivan Perez
latest: 0.0.3.3
description-type: haddock
description: ''
license-name: BSD-3-Clause
