homepage: http://github.com/relrod/doctest-discover-noaeson
changelog-type: ''
hash: 79f62a00ff10acba4f850730ed2ffe99d5637bdfdb48f6fc4b92f03fbbb20a45
test-bench-deps:
  base: ! '>4 && <5'
  doctest: -any
  doctest-discover-configurator: -any
maintainer: ricky@elrod.me
synopsis: Easy way to run doctests via cabal (no aeson dependency, uses configurator
  instead)
changelog: ''
basic-deps:
  bytestring: ==0.10.*
  base: ==4.*
  configurator: ==0.3.*
  filepath: ! '>=1.2 && <1.4'
  doctest: ! '>=0.9'
  directory: ! '>=1.1 && <1.3'
all-versions:
- 0.1.0.6
author: Karun Ramakrishnan, Ricky Elrod
latest: 0.1.0.6
description-type: haddock
description: doctest-discover provides an easy way to run doctests via cabal (uses
  configurator instead of aeson)
license-name: LicenseRef-PublicDomain
