homepage: https://github.com/ChrisPenner/rasa/
changelog-type: ''
hash: 4f91c39c608392b763a69727430d576633ea654634a98fdbd19cf61094e3795d
test-bench-deps: {}
maintainer: christopher.penner@gmail.com
synopsis: Example user config for Rasa
changelog: ''
basic-deps:
  rasa-ext-vim: ! '>=0.1.6 && <0.2'
  base: ! '>=4.8 && <5'
  yi-rope: ! '>=0.7.0.2 && <0.8'
  rasa-ext-views: ! '>=0.1.4 && <0.2'
  data-default: ! '>=0.7.1.1 && <0.8'
  lens: ==4.14.*
  rasa-ext-logger: ! '>=0.1.3 && <0.2'
  rasa-ext-slate: ! '>=0.1.7 && <0.2'
  rasa-ext-files: ! '>=0.1.4 && <0.2'
  mtl: ! '>=2.2.1 && <2.3'
  rasa-ext-cursors: ! '>=0.1.6 && <0.2'
  rasa: ! '>=0.1.10 && <0.2'
all-versions:
- 0.1.0.0
- 0.1.1
- 0.1.2
- 0.1.3
- 0.1.4
author: Chris Penner
latest: 0.1.4
description-type: haddock
description: Example user config for Rasa
license-name: GPL-3.0-only
