homepage: https://github.com/hercules-ci/arion#readme
changelog-type: markdown
hash: 11fab14dc0b4ec883f46838471a758d5c7595f6211bb9f96588c03efdd44bcde
test-bench-deps:
  bytestring: -any
  lens-aeson: -any
  unix: -any
  base: ^>=4.12.0.0
  aeson-pretty: -any
  hspec: -any
  text: -any
  process: -any
  async: -any
  protolude: -any
  arion-compose: -any
  lens: -any
  temporary: -any
  QuickCheck: -any
  aeson: -any
  directory: -any
maintainer: robert@hercules-ci.com
synopsis: Run docker-compose with help from Nix/NixOS
changelog: |
  # Revision history for Arion

  ## Unreleased

  ## 0.1.1.0 -- 2020-03-19

  * Support Nixpkgs 20.03
  * Fixes for macOS

  ## 0.1.0.0 -- 2019-10-04

  * First released version. Released on an unsuspecting world.
basic-deps:
  bytestring: -any
  lens-aeson: -any
  unix: -any
  base: ! '>=4.12.0.0 && <4.13'
  aeson-pretty: -any
  text: -any
  process: -any
  async: -any
  protolude: -any
  arion-compose: -any
  lens: -any
  temporary: -any
  optparse-applicative: -any
  aeson: -any
  directory: -any
all-versions:
- 0.1.0.0
- 0.1.1.0
author: Robert Hensing
latest: 0.1.1.0
description-type: text
description: |
  Arion is a tool for building and running applications that
  consist of multiple docker containers using NixOS modules.
  It has special support for docker images that are built with Nix,
  for a smooth development experience and improved performance.


  # https://docs.hercules-ci.com/arion/[Intro and Documentation]
license-name: Apache-2.0
