homepage: https://higherkindness.io/mu-haskell/
changelog-type: ''
hash: 430936a89e3ba7f897e9463de8ac553d875da7db5fe335dc123188decb353e8e
test-bench-deps: {}
maintainer: alejandro.serrano@47deg.com
synopsis: Metrics support for Mu using Prometheus
changelog: ''
basic-deps:
  wai: '>=3.2 && <4'
  base: '>=4.12 && <5'
  text: '>=1.2 && <2'
  monad-control: '>1 && <2'
  lifted-base: '>=0.2 && <0.3'
  wai-middleware-prometheus: '>1 && <2'
  mu-rpc: ==0.4.*
  prometheus-client: '>1 && <2'
all-versions:
- 0.4.0.0
author: Alejandro Serrano
latest: 0.4.0.0
description-type: haddock
description: Get metrics of your running Mu servers using Prometheus
license-name: Apache-2.0
