homepage: https://github.com/etorreborre/producer-hs#readme
changelog-type: ''
hash: f882d20a654d06bbd57c692d8c433c1fee11d0f3a285a45330d459c437b3531b
test-bench-deps:
  checkers: -any
  base: -any
  producer: -any
  tasty-auto: -any
  tasty-quickcheck: -any
  tasty-hunit: -any
  tasty: -any
  QuickCheck: -any
maintainer: etorreborre@yahoo.com
synopsis: Simple streaming datatype
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
all-versions:
- 0.1.0.0
author: Eric Torreborre
latest: 0.1.0.0
description-type: markdown
description: ! '![Build status](https://travis-ci.org/etorreborre/producer-hs.svg?branch=master)


  # Producer


  Simple streaming library for Haskell

'
license-name: MIT
