homepage: https://github.com/tomjaguarpaw/product-profunctors
changelog-type: markdown
hash: 82817d9b9710257729fde04fb41129d103df25b7e9ec041780ee6e5585bec942
test-bench-deps:
  base: ==4.*
  criterion: -any
  product-profunctors: -any
  deepseq: -any
  profunctors: -any
maintainer: Purely Agile
synopsis: product-profunctors
changelog: |
  # 0.11.0.0

  * Added `makeAdaptorAndInstanceInferrable` which has better inference
    properties, at the cost having to turn on `UndecidableInstances`.
    The tuple instances are now made by this method too.

  # 0.10.0.1

  * Added `Data.Profunctor.Product.Examples`

  # 0.10.0.0

  * Removed `ProductContravariant`, `AndArrow`, `defaultContravariantProduct`,
    `PPOfContravariant`, `unPPOfContravariant`, `cdef`

  * Deprecated `defaultEmpty`, `defaultProfunctorProduct`, `defaultPoint`

  # 0.9.0.0

  * Added more `ProductProfunctor/SumProfunctor` instances including for
    types in `Data.Bifunctor`

  * Added `Data.Profunctor.Product.Adaptor` which derives
    `genericAdaptor` with `Generic`

  * Added ability to derive `Default` instance with `Generic`

  Sorry, we didn't track changes before version 0.9.0.0
basic-deps:
  base: '>=4.5 && <5'
  tagged: '>=0.0 && <1'
  bifunctors: '>=5.4 && <6.0'
  contravariant: '>=0.4 && <1.6'
  template-haskell: -any
  profunctors: '>=5 && <5.6'
all-versions:
- '0.5'
- '0.6'
- 0.6.1
- 0.6.3
- 0.6.3.1
- 0.7.0.2
- 0.7.1.0
- 0.8.0.2
- 0.8.0.3
- 0.9.0.0
- 0.10.0.0
- 0.10.0.1
- 0.11.0.0
author: Purely Agile
latest: 0.11.0.0
description-type: markdown
description: |
  # product-profunctors [![Hackage version](https://img.shields.io/hackage/v/product-profunctors.svg?label=Hackage)](https://hackage.haskell.org/package/product-profunctors) [![Linux build status](https://img.shields.io/travis/tomjaguarpaw/product-profunctors/master.svg?label=Linux%20build)](https://travis-ci.org/tomjaguarpaw/product-profunctors)

  ## Backup maintainers

  In the event of the main developer becoming unreachable, please
  contact the following who are authorised to make bugfixes and
  dependency version bumps:

  * Adam Bergmark
  * Erik Hesselink
  * Oliver Charles
license-name: BSD-3-Clause
