homepage: ''
changelog-type: ''
hash: a2cabd32048d2e655101d0687d9a44f2f20eaf4ec423957df1020e8698174d6b
test-bench-deps: {}
maintainer: None
synopsis: Product category
changelog: ''
basic-deps:
  base: '>=4.10 && <5'
  category: -any
all-versions:
- 0.1.0.0
author: M Farkas-Dyck
latest: 0.1.0.0
description-type: haddock
description: ''
license-name: BSD-3-Clause
