homepage: http://github.com/khibino/haskell-product-isomorphic
changelog-type: ''
hash: cf3f79b71a9f0b19f7ae96981a76d605ea704757fbe96740a25d16d2519e2490
test-bench-deps:
  base: <5
  product-isomorphic: -any
  template-haskell: -any
maintainer: ex8k.hibino@gmail.com
synopsis: Weaken applicative functor on products
changelog: ''
basic-deps:
  base: ! '>=4.5 && <5'
  th-data-compat: -any
  template-haskell: -any
all-versions:
- '0.0.1.0'
- '0.0.2.0'
- '0.0.3.0'
- '0.0.3.1'
- '0.0.3.2'
author: Kei Hibino
latest: '0.0.3.2'
description-type: haddock
description: ! 'Weaken applicative functor which allows only product

  construction. Product constructions and deconstructions

  are always isomorphic.'
license-name: BSD3
