homepage: https://github.com/fimad/prometheus-haskell
changelog-type: markdown
hash: 883a5e2637e37b6a522798260956dc33c691fe139ede1920c79def18cc9ed277
test-bench-deps: {}
maintainer: ollie@ocharles.org.uk
synopsis: Export metrics from /proc for the current process
changelog: |
  # 0.1.0.0 -- 2019-01-15

  * Initial release.
basic-deps:
  unix: ! '>=2.7 && <2.8'
  base: ! '>=4.10 && <4.13'
  filepath: ! '>=1.4 && <1.5'
  regex-applicative: ! '>=0.3 && <0.4'
  prometheus-client: ! '>=1.0.0 && <1.1'
  unix-memory: ! '>=0.1 && <0.2'
all-versions:
- 0.1.0.0
author: Ollie Charles
latest: 0.1.0.0
description-type: haddock
description: ''
license-name: BSD-3-Clause
