homepage: https://github.com/fimad/prometheus-haskell
changelog-type: ''
hash: 0359ee348b7cdbc2220351eaa94a3ce4784f4ddd630241e7529224b0eba4dd80
test-bench-deps:
  base: ! '>=4.7 && <5'
  doctest: -any
  prometheus-client: -any
maintainer: willcoster@gmail.com
synopsis: Metrics exposing GHC runtime information for use with prometheus-client.
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  utf8-string: ! '>=0.3'
  prometheus-client: -any
all-versions:
- '0.1.0.0'
- '0.1.0.1'
- '0.1.1'
- '0.2.0'
- '0.3.0'
author: Will Coster
latest: '0.3.0'
description-type: haddock
description: Metrics exposing GHC runtime information for use with prometheus-client.
license-name: Apache-2.0
