homepage: https://github.com/fimad/prometheus-haskell
changelog-type: ''
hash: 0f4ecbefa810bd847e66c498ab3387bf21e426525a7c9a94841973c582719ba3
test-bench-deps:
  base: ! '>=4.7 && <5'
  doctest: -any
  prometheus-client: -any
maintainer: willcoster@gmail.com
synopsis: Metrics exposing GHC runtime information for use with prometheus-client.
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  text: -any
  utf8-string: ! '>=0.3'
  prometheus-client: ! '>=1.0.0 && <1.1'
all-versions:
- '0.1.0.0'
- '0.1.0.1'
- '0.1.1'
- '0.2.0'
- '0.3.0'
- '1.0.0'
author: Will Coster
latest: '1.0.0'
description-type: haddock
description: Metrics exposing GHC runtime information for use with prometheus-client.
license-name: Apache-2.0
