homepage: ''
changelog-type: markdown
hash: a65a8c02e47e5bd6eccfd9ea9cbefcbc01f109be080a3832d759e1b3f33a673a
test-bench-deps: {}
maintainer: ian.shipman@bitnomial.com
synopsis: Instrument a wai application with various metrics
changelog: |
  # Revision history for prometheus-wai-middleware

  ## 1.0.0.0 - 2020-06-26

  First version. Released on an unsuspecting world.
basic-deps:
  warp: '>=3.2 && <3.5'
  wai: ==3.2.*
  base: '>=4.12 && <5'
  text: ^>=1.2
  clock: ^>=0.8
  async: ^>=2.2
  prometheus-wai-middleware: -any
  containers: '>=0.5 && <0.7'
  prometheus: ==2.2.*
  http-types: '>=0.8 && <0.13'
all-versions:
- 1.0.0.0
- 1.0.1.0
author: Ian Shipman
latest: 1.0.1.0
description-type: haddock
description: See https://github.com/bitnomial/prometheus-wai-middleware/tree/master/readme.md
license-name: BSD-3-Clause
