homepage: https://github.com/fimad/prometheus-haskell
changelog-type: markdown
hash: 84f56e9c886be777d5afd14fc57fff156137a611f0db0fe080b97fc602103c23
test-bench-deps: {}
maintainer: ollie@ocharles.org.uk
synopsis: Export metrics from /proc for the current process
changelog: |
  # 0.1.3.0 -- 2020-06-17

  * Support base-4.14 and GHC 8.10.

  # 0.1.2.0 -- 2019-09-18

  * Support base-4.13 and GHC 8.8.

  # 0.1.1.0 -- 2019-05-23

  * Change all use of `Int` to `Int64`. `Int` is only guaranteed to be able to
    represent values up to 2^29-1, but entries in /proc/stat can often exceed that
    (for example processes with a high resident memory usage) on 32-bit machines.

  * Export `process_open_fds`, a count of the number of entries in
    `/proc/$PID/fd`.

  * Export `process_max_fds`, which exports the soft ulimit of the maximum number
    of file descriptors this process may open.

  # 0.1.0.0 -- 2019-01-15

  * Initial release.
basic-deps:
  unix: '>=2.7 && <2.8'
  base: '>=4.10 && <4.15'
  text: '>=0.7 && <1.3'
  filepath: '>=1.4 && <1.5'
  regex-applicative: '>=0.3 && <0.4'
  prometheus-client: '>=1.0.0 && <1.1'
  unix-memory: '>=0.1 && <0.2'
  directory: '>=1.2.5.0 && <1.4'
all-versions:
- 0.1.0.0
- 0.1.1.0
- 0.1.2.0
- 0.1.3.0
author: Ollie Charles
latest: 0.1.3.0
description-type: haddock
description: ''
license-name: BSD-3-Clause
