homepage: http://www.yesodweb.com/
changelog-type: ''
hash: 0d622fd91f5c82a3ae54849a9f55e15b39dcc6240f9f2119151362255cd7334e
test-bench-deps:
  bytestring: -any
  base: ! '>=4.3 && <5'
  hspec: ! '>=1.3'
  text: ! '>=0.5'
  HUnit: ! '>=1.2 && <1.3'
  path-pieces: -any
  containers: -any
  yesod-routes: -any
  template-haskell: -any
maintainer: Michael Snoyman <michael@snoyman.com>
synopsis: Efficient routing for Yesod. (deprecated)
changelog: ''
basic-deps:
  base: ! '>=4 && <5'
  text: ! '>=0.5'
  path-pieces: ! '>=0.1 && <0.2'
  containers: ! '>=0.2'
  template-haskell: -any
  vector: ! '>=0.8 && <0.11'
all-versions:
- 0.0.1
- 1.0.0
- 1.0.1
- 1.0.1.1
- 1.0.1.2
- 1.1.0
- 1.1.0.1
- 1.1.0.2
- 1.1.1
- 1.1.1.1
- 1.1.2
- 1.2.0
- 1.2.0.1
- 1.2.0.2
- 1.2.0.3
- 1.2.0.4
- 1.2.0.5
- 1.2.0.6
- 1.2.0.7
author: Michael Snoyman <michael@snoyman.com>
latest: 1.2.0.7
description-type: haddock
description: Provides an efficient routing system, a parser and TH code generation.
license-name: MIT
