homepage: https://github.com/iokasimov/pipeline
changelog-type: markdown
hash: faddf28d504d6954b5036d68c7c2cf089c482d1e04abafe3b287f88b64d75dc9
test-bench-deps: {}
maintainer: Murat Kasimov <iokasimov.m@gmail.com>
synopsis: Continuation patterns
changelog: ''
basic-deps:
  base: ==4.*
  transformers: -any
all-versions:
- 0.1.0
author: Murat Kasimov
latest: 0.1.0
description-type: haddock
description: Lightweight and fast streaming
license-name: BSD-3-Clause
