homepage: https://github.com/yi-editor/yi#readme
changelog-type: ''
hash: 086d19c2e50b82e197fab96921d0528e6444e60689b60ab8bea39498d7ef19f7
test-bench-deps: {}
maintainer: Yi developers <yi-devel@googlegroups.com>
synopsis: Dynamic configuration support for Yi
changelog: ''
basic-deps:
  microlens-platform: -any
  dyre: ! '>=0.8.11'
  base: ! '>=4.8 && <5'
  yi-rope: ! '>=0.8'
  text: ! '>=1.0'
  data-default: -any
  mtl: ! '>=0.1.0.1'
  transformers-base: -any
  yi-core: ! '>=0.17.0'
all-versions:
- '0.14.0'
- '0.14.1'
- '0.15.0'
- '0.16.0'
- '0.17.0'
author: ''
latest: '0.17.0'
description-type: haddock
description: ''
license-name: GPL-2
