homepage: https://github.com/yi-editor/yi#readme
changelog-type: ''
hash: 02e893b58a0f9c93c7464721c270247526f33cc36109c6ae24fbefb98832a72e
test-bench-deps: {}
maintainer: Yi developers <yi-devel@googlegroups.com>
synopsis: Dynamic configuration support for Yi
changelog: ''
basic-deps:
  microlens-platform: -any
  dyre: '>=0.8.11'
  base: '>=4.8 && <5'
  yi-rope: '>=0.10'
  text: '>=1.0'
  data-default: -any
  mtl: '>=0.1.0.1'
  transformers-base: -any
  yi-core: '>=0.19'
all-versions:
- 0.14.0
- 0.14.1
- 0.15.0
- 0.16.0
- 0.17.0
- 0.17.1
- 0.18.0
- 0.19.0
author: ''
latest: 0.19.0
description-type: haddock
description: ''
license-name: GPL-2.0-only
