homepage: https://github.com/yi-editor/yi#readme
changelog-type: ''
hash: 96ad26749d5ac7b4b5b2fa894f13dac6ea423335d50be3ca50aebddf8fbfc55b
test-bench-deps: {}
maintainer: Yi developers <yi-devel@googlegroups.com>
synopsis: Dynamic configuration support for Yi
changelog: ''
basic-deps:
  microlens-platform: -any
  dyre: ! '>=0.8.11'
  base: ! '>=4.8 && <5'
  yi-rope: ! '>=0.10'
  text: ! '>=1.0'
  data-default: -any
  mtl: ! '>=0.1.0.1'
  transformers-base: -any
  yi-core: ! '>=0.17'
all-versions:
- '0.14.0'
- '0.14.1'
- '0.15.0'
- '0.16.0'
- '0.17.0'
- '0.17.1'
author: ''
latest: '0.17.1'
description-type: haddock
description: ''
license-name: GPL-2
