homepage: ''
changelog-type: ''
hash: 536eacac6f54fbeb3e823d5b751eaa8cf1bb45a69f1d0bf54bdbff6245eb93e9
test-bench-deps: {}
maintainer: jon@jonmsterling.com
synopsis: Configuration types, parsers & renderers for AWS services
changelog: ''
basic-deps:
  base-unicode-symbols: -any
  bytestring: ! '>=0.10.4.0'
  base: ! '>=4.7 && <5.0'
  aws: ! '>=0.11'
  text: ! '>=1.2.0.3'
  aws-kinesis: ! '>=0.1.5'
  configuration-tools: ! '>=0.2.12'
  mtl: ! '>=2.1.3.1'
  transformers: ! '>=0.4.2.0'
  aws-general: ! '>=0.2.2'
all-versions:
- 0.1.0.0
author: Lars Kuhtz & Jon Sterling
latest: 0.1.0.0
description-type: haddock
description: Configuration types, parsers & renderers for AWS services, using configuration-tools.
license-name: Apache-2.0
