homepage: ''
changelog-type: ''
hash: 2b209190f13d49f6b1386a3ac34f35fbd877134d1f6412234c92183894331d05
test-bench-deps: {}
maintainer: jacinablackbox@yahoo.com
synopsis: Methods for composing monads.
changelog: ''
basic-deps:
  free: ==5.1
  base: ! '>=4 && <=5'
  mtl: ! '>=2.2'
  mmorph: ==1.0.*
  transformers: -any
all-versions:
- 0.1.0.0
- 0.2.0.0
- 0.3.0.0
- 0.4.0.0
- 0.5.0.0
- 0.6.0.0
- 0.7.0.0
- 0.8.0.0
- 0.8.1.0
- 0.8.2.0
- 0.8.3.0
- 0.8.3.1
- 0.8.4.0
- 0.8.4.1
- 0.8.4.2
- 0.9.0.0
author: James Candy
latest: 0.9.0.0
description-type: haddock
description: |
  Methods for composing monads.

  The I/O monad transformer, PlusMonad, and Linear modules are deprecated. Their use is discouraged. This package is now about automatic monad lifting; and includes a rigorous implementation of Luth and Ghani coproducts structured around the Free monad.
license-name: BSD-3-Clause
