homepage: ''
changelog-type: text
hash: df455083a2380b4c0cd024988b991898c5ff23e3bcb0a3243dac79e7f57e3dd2
test-bench-deps:
  base: -any
  doctest: ! '>=0.13'
maintainer: Joey Hess <id@joeyh.name>
synopsis: home (etc) automation using reactive-banana
changelog: ! "reactive-banana-automation (0.3.0) upstream; urgency=medium\n\n  * EventSource
  is now a data type with an extra value for expansion.\n    (API change)\n  * Added
  newEventSource, sensorUnavailable, sensedEventBehavior,\n    and automationStepper.\n\n
  -- Joey Hess <id@joeyh.name>  Sat, 05 May 2018 19:27:56 -0400\n\nreactive-banana-automation
  (0.2.0) upstream; urgency=medium\n\n  * Automation is now a newtype. (API change)\n
  \ * Monoid instance for Automation to allow easily combining them.\n    (Note that
  in 0.1, there were inherited Monoid and Monad instances\n    for Automation, that
  did not work in a reasonable way.)\n\n -- Joey Hess <id@joeyh.name>  Thu, 03 May
  2018 18:54:04 -0400\n\nreactive-banana-automation (0.1.2) upstream; urgency=medium\n\n
  \ * Added ClockSignal and related functions.\n  * Functor instances for Sensed and
  Timestamped.\n  * Added more Timestamp instances.\n  * Generalized sensedAt to work
  with any Timestamp.\n  * Added several more examples, including a night light,\n
  \   a behavior for a tipping bucket rain gauge, and sprinkers\n    that only run
  when it's not rained recently.\n\n -- Joey Hess <id@joeyh.name>  Thu, 03 May 2018
  17:28:32 -0400\n\nreactive-banana-automation (0.1.1) upstream; urgency=medium\n\n
  \ * Fix build with ghc 8.2 and reactive-banana 1.2.\n\n -- Joey Hess <id@joeyh.name>
  \ Sat, 21 Apr 2018 20:14:41 -0400\n\nreactive-banana-automation (0.1) upstream;
  urgency=low\n\n  * First release.\n\n -- Joey Hess <id@joeyh.name>  Sat, 21 Apr
  2018 15:50:43 -0400\n"
basic-deps:
  stm: (>=2.4 && <2.5)
  base: (>=4.6 && <5.0)
  time: (>=1.6 && <1.9)
  reactive-banana: (>=1.1 && <1.3)
all-versions:
- '0.1'
- '0.1.1'
- '0.1.2'
- '0.2.0'
- '0.3.0'
author: Joey Hess
latest: '0.3.0'
description-type: haddock
description: ! 'Functional Reactive Programming is a natural fit for home automation,

  which involves sensor values that vary over time and are used to control

  actuators.


  This library provides a framework and some useful types for

  using the reactive-banana FRP library for home automation.'
license-name: AGPL-3
