homepage: ''
changelog-type: text
hash: a94ee9e664b8857f88890d2496e509cb55cb49a0d9763ffce3efd4b85691fcf7
test-bench-deps:
  base: -any
  doctest: ! '>=0.15'
maintainer: Joey Hess <joey@kitenet.net>
synopsis: home (etc) automation using reactive-banana
changelog: ! "reactive-banana-automation (0.1) upstream; urgency=low\n\n  * First
  release.\n\n -- Joey Hess <id@joeyh.name>  Sat, 21 Apr 2018 15:50:43 -0400\n"
basic-deps:
  stm: (>=2.4 && <2.5)
  base: (>=4.6 && <5.0)
  time: (>=1.6 && <1.7)
  reactive-banana: (>=1.1 && <1.2)
all-versions:
- '0.1'
author: Joey Hess
latest: '0.1'
description-type: haddock
description: ! 'Functional Reactive Programming is a natural fit for home automation,

  which involves sensor values that vary over time and are used to control

  actuators.


  This library provides a framework and some useful types for

  using the reactive-banana FRP library for home automation.'
license-name: AGPL-3
