homepage: ''
changelog-type: markdown
hash: a8ff54406839351c92124c4724dbe35735705f001c76a611d3686fb36d4bf236
test-bench-deps: {}
maintainer: jpgarcia@fing.edu.uy
synopsis: Abstraction to manage user defined Type Errors
changelog: |
  # Revision history for Require

  ## 0.5.3.0 -- YYYY-mm-dd

  * First version. Released on an unsuspecting world.
basic-deps:
  base: '>=4.11.0 && <4.15'
all-versions:
- 0.6.0.0
author: Juan García-Garland
latest: 0.6.0.0
description-type: haddock
description: Require framework, abstraction to manage user defined Type Errors
license-name: GPL-3.0-only
