homepage: https://github.com/scrive/kontra-config
changelog-type: ''
hash: c4bd3f416488580ac7f42f00b1173249f92db3c8a4940beba5cb985f5eb9ee8f
test-bench-deps: {}
maintainer: Gracjan Polak <gracjan@scrive.com>, Jonathan Jouty <jonathan@scrive.com>,
  Mikhail Glushenkov <mikhail@scrive.com>
synopsis: JSON config file parsing based on unjson
changelog: ''
basic-deps:
  exceptions: ! '>=0.6'
  bytestring: -any
  base: <5
  text: -any
  data-default: -any
  utf8-string: -any
  transformers-base: -any
  unjson: -any
  yaml: -any
all-versions:
- '0.1'
author: Scrive AB
latest: '0.1'
description-type: markdown
description: ! '# kontra-config [![Hackage version](https://img.shields.io/hackage/v/kontra-config.svg?label=Hackage)](https://hackage.haskell.org/package/kontra-config)
  [![Build Status](https://secure.travis-ci.org/scrive/kontra-config.svg?branch=master)](http://travis-ci.org/scrive/kontra-config)


  A library for reading JSON configuration files. Based on unjson.

'
license-name: BSD-3-Clause
