homepage: https://github.com/chpatrick/solga
changelog-type: ''
hash: 47c65ca98998a9e6bdd533a724f5ee3e0b886a283a152959cc9fe4c7875cd38f
test-bench-deps: {}
maintainer: chpatrick@gmail.com
synopsis: Swagger generation for Solga
changelog: ''
basic-deps:
  insert-ordered-containers: -any
  bytestring: -any
  base: ! '>=4.8 && <5'
  unordered-containers: -any
  text: -any
  dlist: -any
  lens: -any
  mtl: -any
  swagger2: ! '>=2.1'
  solga: -any
  http-types: -any
all-versions:
- 0.1.0.0
- 0.1.0.1
- 0.1.0.2
author: Patrick Chilton
latest: 0.1.0.2
description-type: haddock
description: Swagger generation for Solga
license-name: MIT
